//go:build local

package store

import (
	"github.com/funtimecoding/go-library/pkg/assert"
	library "github.com/funtimecoding/go-library/pkg/constant"
	"github.com/funtimecoding/go-library/pkg/errors"
	"github.com/funtimecoding/go-library/pkg/tool/goqueryd/constant"
	"os"
	"path/filepath"
	"testing"
)

func TestIndexNewDocuments(t *testing.T) {
	s, _ := indexedTestStore(t)
	defer s.Close()
	status := s.MustStatus()
	assert.Integer(t, 5, status.TotalDocuments)
}

func TestIndexUnchanged(t *testing.T) {
	s, _ := indexedTestStore(t)
	defer s.Close()
	result := s.Index("test")
	assert.Integer(t, 0, result.Indexed)
	assert.Integer(t, 0, result.Updated)
	assert.Integer(t, 5, result.Unchanged)
}

func TestIndexUpdatedContent(t *testing.T) {
	s, _ := openTestStore(t)
	defer s.Close()
	directory := t.TempDir()
	writeFixture(t, directory, "doc.md", "# Original\n\nOriginal content.\n")
	s.AddCollection("test", directory, constant.DefaultGlob)
	s.Index("test")
	writeFixture(t, directory, "doc.md", "# Updated\n\nUpdated content.\n")
	result := s.Index("test")
	assert.Integer(t, 0, result.Indexed)
	assert.Integer(t, 1, result.Updated)
}

func TestIndexRemovedDocument(t *testing.T) {
	s, _ := openTestStore(t)
	defer s.Close()
	directory := t.TempDir()
	writeFixture(t, directory, "keep.md", "# Keep\n\nStays.\n")
	writeFixture(t, directory, "remove.md", "# Remove\n\nGoes away.\n")
	s.AddCollection("test", directory, constant.DefaultGlob)
	s.Index("test")
	errors.PanicOnError(os.Remove(filepath.Join(directory, "remove.md")))
	result := s.Index("test")
	assert.Integer(t, 1, result.Removed)
	status := s.MustStatus()
	assert.Integer(t, 1, status.TotalDocuments)
}

func TestIndexSkipsHiddenFiles(t *testing.T) {
	s, _ := openTestStore(t)
	defer s.Close()
	directory := t.TempDir()
	writeFixture(t, directory, "visible.md", "# Visible\n\nContent.\n")
	writeFixture(t, directory, ".hidden/secret.md", "# Secret\n\nHidden.\n")
	s.AddCollection("test", directory, constant.DefaultGlob)
	result := s.Index("test")
	assert.Integer(t, 1, result.Indexed)
}

func TestIndexSkipsGeneratedFiles(t *testing.T) {
	s, _ := openTestStore(t)
	defer s.Close()
	directory := t.TempDir()
	writeFixture(
		t,
		directory,
		"real.go",
		"package foo\n\nfunc Real() {}\n",
	)
	writeFixture(
		t,
		directory,
		library.GeneratedFile,
		"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n",
	)
	s.AddCollection("test", directory, "**/*.go")
	result := s.Index("test")
	assert.Integer(t, 1, result.Indexed)
}
