package response

type InstalledFormula struct {
	Name                          string                `json:"name"`
	FullName                      string                `json:"full_name"`
	Tap                           string                `json:"tap"`
	OldNames                      []string              `json:"oldnames"`
	Aliases                       []string              `json:"aliases"`
	VersionedFormulae             []string              `json:"versioned_formulae"`
	Desc                          string                `json:"desc"`
	License                       *string               `json:"license"`
	Homepage                      string                `json:"homepage"`
	Versions                      FormulaVersions       `json:"versions"`
	Locator                       FormulaLocator        `json:"urls"`
	Revision                      int                   `json:"revision"`
	VersionScheme                 int                   `json:"version_scheme"`
	Autobump                      bool                  `json:"autobump"`
	NoAutobumpMessage             any                   `json:"no_autobump_message"`
	SkipLivecheck                 bool                  `json:"skip_livecheck"`
	Bottle                        Bottle                `json:"bottle"`
	PourBottleOnlyIf              *string               `json:"pour_bottle_only_if"`
	KegOnly                       bool                  `json:"keg_only"`
	KegOnlyReason                 *KegOnlyReason        `json:"keg_only_reason"`
	Options                       []any                 `json:"options"`
	BuildDependencies             []string              `json:"build_dependencies"`
	Dependencies                  []string              `json:"dependencies"`
	TestDependencies              []string              `json:"test_dependencies"`
	RecommendedDependencies       []any                 `json:"recommended_dependencies"`
	OptionalDependencies          []any                 `json:"optional_dependencies"`
	UsesFromMacos                 []any                 `json:"uses_from_macos"`
	UsesFromMacosBounds           []MacosBound          `json:"uses_from_macos_bounds"`
	Requirements                  []Requirement         `json:"requirements"`
	ConflictsWith                 []string              `json:"conflicts_with"`
	ConflictsWithReasons          []string              `json:"conflicts_with_reasons"`
	LinkOverwrite                 []string              `json:"link_overwrite"`
	Caveats                       *string               `json:"caveats"`
	Installed                     []FormulaInstallation `json:"installed"`
	LinkedKeg                     *string               `json:"linked_keg"`
	Pinned                        bool                  `json:"pinned"`
	Outdated                      bool                  `json:"outdated"`
	Deprecated                    bool                  `json:"deprecated"`
	DeprecationDate               *string               `json:"deprecation_date"`
	DeprecationReason             *string               `json:"deprecation_reason"`
	DeprecationReplacementFormula any                   `json:"deprecation_replacement_formula"`
	DeprecationReplacementCask    any                   `json:"deprecation_replacement_cask"`
	Disabled                      bool                  `json:"disabled"`
	DisableDate                   *string               `json:"disable_date"`
	DisableReason                 *string               `json:"disable_reason"`
	DisableReplacementFormula     any                   `json:"disable_replacement_formula"`
	DisableReplacementCask        any                   `json:"disable_replacement_cask"`
	PostInstallDefined            bool                  `json:"post_install_defined"`
	Service                       *FormulaService       `json:"service"`
	TapGitHead                    string                `json:"tap_git_head"`
	RubySourcePath                string                `json:"ruby_source_path"`
	RubySourceChecksum            RubySourceChecksum    `json:"ruby_source_checksum"`
	HeadDependencies              HeadDependencies      `json:"head_dependencies,omitempty"`
}
