---
version: '3'
tasks:
  default: {cmds: [{task: lint}, {task: test}, {task: build}], silent: true}
  pre-push: {cmds: [{task: lint}, {task: test}], silent: true}
  lint:
    cmds:
    - |
      mkdir -p fixture/lint/empty_directory
      golint --fix --skip fixture,tmp
      #command -v gowait >/dev/null && gowait --process golangci-lint || true
      golangci-lint run
    silent: true
  test: {cmds: ['gotestsum --format standard-quiet'], silent: true}
  check:
    cmds:
    - gosec -fmt=json -out=tmp/gosec.json -stdout -verbose=text -no-fail ./...
    silent: true
  build: {cmds: ['go run cmd/gobuild/main.go'], silent: true}
  update:
    cmds:
    # k8s.io/apimachinery: Cilium is not ready for 0.31.0
    # github.com/google/gnostic-models: 0.7.0 has bad imports
    - |
      goupdate \
        --downgrade k8s.io/apimachinery@v0.30.14 \
        --downgrade github.com/google/gnostic-models@v0.6.9
    silent: true
  tool:
    cmds:
    - |
      go install gotest.tools/gotestsum@latest
      go install github.com/funtimecoding/go-library/cmd/golint@latest
      go install github.com/funtimecoding/go-library/cmd/gobuild@latest
      curl -sSfL \
        https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh \
        | sh -s -- -b $(go env GOPATH)/bin
      go install github.com/boumenot/gocover-cobertura@latest
    silent: true
  install:
    cmds:
    - |
      go run cmd/gobuild/main.go --copy-to-bin gobuild
      gobuild --copy-to-bin
    silent: true
  coverage:
    cmds:
    - |
      mkdir -p tmp
      go test -coverprofile=tmp/coverage.txt -covermode count ./...
      gocover-cobertura <tmp/coverage.txt >tmp/coverage.xml
    silent: true
  server-check:
    cmds:
    - gobuild --copy-to-bin gochk
    - tmp/deploy.sh
    silent: true
