package argument

const (
	Branch      = "branch"
	Downgrade   = "downgrade"
	Exclusive   = "exclusive"
	Executable  = "executable"
	Header      = "header"
	Host        = "host"
	Interactive = "interactive"
	Locator     = "locator"
	Main        = "main"
	Message     = "message"
	Name        = "name"
	Output      = "output"
	Owner       = "owner"
	Package     = "package"
	Password    = "password"
	Path        = "path"
	Project     = "project"
	Replace     = "replace"
	Repository  = "repository"
	Tag         = "tag"
	Template    = "template"
	Token       = "token"
	User        = "user"
	Verbose     = "verbose"
	Version     = "version"
)
