package argument

const (
	Branch      = "branch"
	Cluster     = "cluster"
	Container   = "container"
	Core        = "core"
	Downgrade   = "downgrade"
	Download    = "download"
	Exclusive   = "exclusive"
	Executable  = "executable"
	File        = "file"
	Header      = "header"
	Host        = "host"
	Interactive = "interactive"
	Key         = "key"
	Locator     = "locator"
	Main        = "main"
	Memory      = "memory"
	Message     = "message"
	Name        = "name"
	Namespace   = "namespace"
	Node        = "node"
	Output      = "output"
	Owner       = "owner"
	Package     = "package"
	Password    = "password"
	Path        = "path"
	Pod         = "pod"
	Pretend     = "pretend"
	Project     = "project"
	Replace     = "replace"
	Repository  = "repository"
	Tag         = "tag"
	Template    = "template"
	Token       = "token"
	Topic       = "topic"
	User        = "user"
	Verbose     = "verbose"
	Version     = "version"
)
