package gofix

import (
	"github.com/funtimecoding/go-library/pkg/assert"
	"github.com/funtimecoding/go-library/pkg/constant"
	"github.com/funtimecoding/go-library/pkg/lint/analyzer/testutil"
	"github.com/funtimecoding/go-library/pkg/lint/output"
	"path/filepath"
	"testing"
)

func TestFix(t *testing.T) {
	directory := writeTestModule(t)
	r := output.NewResultsWithDirectory(directory)
	all, fileSet := load(directory, []string{"./..."})
	violations := findViolations(all)
	edits := buildAllEdits(fileSet, all, violations, r)
	applyEdits(fileSet, edits, directory, false)
	loadedFiles := buildLoadedFiles(all)
	fixUnloadedReferences(violations, loadedFiles, directory, r)
	t.Run(
		"CrossPackageRename",
		func(t *testing.T) {
			assert.String(
				t,
				"package types\n\nfunc DirectoryPath() string { return directoryName }\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"types",
						"directory_path.go",
					),
				),
			)
			assert.String(
				t,
				"package types\n\nvar directoryName = \"test\"\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"types",
						"directory_name.go",
					),
				),
			)
			assert.String(
				t,
				"package types\n\nconst StrayConstant = \"value\"\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"types",
						"stray_const.go",
					),
				),
			)
			assert.String(
				t,
				"package consumer\n\nimport \"testmodule/pkg/types\"\n\nfunc Example() string {\n\t_ = types.StrayConstant\n\n\treturn types.DirectoryPath()\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "consumer", "use.go"),
				),
			)
		},
	)
	t.Run(
		"SkipsInterfaceMethod",
		func(t *testing.T) {
			assert.String(
				t,
				"package impl\n\nimport \"testmodule/pkg/face\"\n\ntype Server struct{}\n\nfunc (s Server) Addr() string { return \"\" }\n\nvar _ face.Worker = Server{}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "impl", "impl.go"),
				),
			)
		},
	)
	t.Run(
		"SkipsGeneratedFile",
		func(t *testing.T) {
			assert.String(
				t,
				"package types\n\n// Code generated by tool DO NOT EDIT.\n\ntype ParamError struct{}\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"types",
						constant.GeneratedFile,
					),
				),
			)
		},
	)
	t.Run(
		"StructFieldGetsMultiCharacter",
		func(t *testing.T) {
			assert.String(
				t,
				"package fields\n\ntype Entry struct {\n\tReference string\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "fields", "entry.go"),
				),
			)
		},
	)
	t.Run(
		"MultiSegmentPrefersMultiCharacter",
		func(t *testing.T) {
			assert.String(
				t,
				"package multi\n\nfunc Example() string {\n\tfooReference := \"x\"\n\n\treturn fooReference\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "multi", "example.go"),
				),
			)
		},
	)
	t.Run(
		"SingleLetterCollisionFallback",
		func(t *testing.T) {
			assert.String(
				t,
				"package collision\n\nfunc Example() string {\n\tr := \"taken\"\n\te := \"test\"\n\n\treturn r + e\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"collision",
						"example.go",
					),
				),
			)
		},
	)
	t.Run(
		"CollisionFallback",
		func(t *testing.T) {
			assert.String(
				t,
				"package abort\n\nfunc Example() string {\n\tt := \"taken\"\n\ta := \"test\"\n\n\treturn t + a\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "abort", "example.go"),
				),
			)
		},
	)
	t.Run(
		"InnerScopeShadow",
		func(t *testing.T) {
			assert.String(
				t,
				"package shadow\n\nfunc Example() string {\n\tm := map[string]string{\"k\": \"x\"}\n\n\tfor _, a := range m {\n\t\tv := a\n\t\t_ = v\n\t}\n\n\treturn \"\"\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "shadow", "example.go"),
				),
			)
		},
	)
	t.Run(
		"ParentScopeShadow",
		func(t *testing.T) {
			assert.String(
				t,
				"package parent\n\nfunc Example() {\n\ts := \"status\"\n\tsources := []string{\"a\"}\n\n\tfor _, o := range sources {\n\t\t_ = s + o\n\t}\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"parent",
						"example.go",
					),
				),
			)
		},
	)
	t.Run(
		"ErrorChainSecond",
		func(t *testing.T) {
			assert.String(
				t,
				"package errs\n\nimport \"fmt\"\n\nfunc Example() {\n\te := fmt.Errorf(\"first\")\n\tf := fmt.Errorf(\"second\")\n\t_ = e\n\t_ = f\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"errs",
						"example.go",
					),
				),
			)
		},
	)
	t.Run(
		"ErrorChainThird",
		func(t *testing.T) {
			assert.String(
				t,
				"package errs\n\nimport \"fmt\"\n\nfunc Triple() {\n\te := fmt.Errorf(\"first\")\n\tf := fmt.Errorf(\"second\")\n\tg := fmt.Errorf(\"third\")\n\t_ = e\n\t_ = f\n\t_ = g\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"errs",
						"triple.go",
					),
				),
			)
		},
	)
	t.Run(
		"ExportedCrossPackageRename",
		func(t *testing.T) {
			assert.String(
				t,
				"package sentinel\n\nimport \"fmt\"\n\nvar ErrorQuit = fmt.Errorf(\"quit\")\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"sentinel",
						"sentinel.go",
					),
				),
			)
			assert.String(
				t,
				"package caller\n\nimport (\n\t\"errors\"\n\t\"testmodule/pkg/sentinel\"\n)\n\nfunc Check(e error) bool {\n\treturn errors.Is(e, sentinel.ErrorQuit)\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"caller",
						"caller.go",
					),
				),
			)
			assert.String(
				t,
				"//go:build ignore\n\npackage tagged\n\nimport (\n\t\"errors\"\n\t\"testmodule/pkg/sentinel\"\n)\n\nfunc Handle(e error) bool {\n\treturn errors.Is(e, sentinel.ErrorQuit)\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"tagged",
						"tagged.go",
					),
				),
			)
		},
	)
	t.Run(
		"ResultEntries",
		func(t *testing.T) {
			applied := filterApplied(r.Entries)
			assertResult(
				t,
				applied,
				"pkg/types/directory_path.go",
				"renamed DirPath → DirectoryPath (2 references)",
			)
			assertResult(
				t,
				applied,
				"pkg/types/directory_name.go",
				"renamed dirName → directoryName (2 references)",
			)
			assertResult(
				t,
				applied,
				"pkg/types/stray_const.go",
				"renamed StrayConst → StrayConstant (2 references)",
			)
			assertResult(
				t,
				applied,
				"pkg/sentinel/sentinel.go",
				"renamed ErrQuit → ErrorQuit (2 references)",
			)
			assertResult(
				t,
				applied,
				"pkg/tagged/tagged.go",
				"renamed ErrQuit → ErrorQuit (unloaded)",
			)
		},
	)
}

func writeTestModule(t *testing.T) string {
	t.Helper()
	directory := t.TempDir()
	testutil.WriteFile(
		t,
		directory,
		"go.mod",
		"module testmodule\n\ngo 1.22\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/types/directory_path.go",
		"package types\n\nfunc DirPath() string { return dirName }\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/types/directory_name.go",
		"package types\n\nvar dirName = \"test\"\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/types/stray_const.go",
		"package types\n\nconst StrayConst = \"value\"\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/types/generated.go",
		"package types\n\n// Code generated by tool DO NOT EDIT.\n\ntype ParamError struct{}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/face/worker.go",
		"package face\n\ntype Worker interface {\n\tAddr() string\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/impl/impl.go",
		"package impl\n\nimport \"testmodule/pkg/face\"\n\ntype Server struct{}\n\nfunc (s Server) Addr() string { return \"\" }\n\nvar _ face.Worker = Server{}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/consumer/use.go",
		"package consumer\n\nimport \"testmodule/pkg/types\"\n\nfunc Example() string {\n\t_ = types.StrayConst\n\n\treturn types.DirPath()\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/fields/entry.go",
		"package fields\n\ntype Entry struct {\n\tRef string\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/multi/example.go",
		"package multi\n\nfunc Example() string {\n\tfooRef := \"x\"\n\n\treturn fooRef\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/collision/example.go",
		"package collision\n\nfunc Example() string {\n\tr := \"taken\"\n\tref := \"test\"\n\n\treturn r + ref\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/abort/example.go",
		"package abort\n\nfunc Example() string {\n\tt := \"taken\"\n\ttx := \"test\"\n\n\treturn t + tx\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/shadow/example.go",
		"package shadow\n\nfunc Example() string {\n\tm := map[string]string{\"k\": \"x\"}\n\n\tfor _, val := range m {\n\t\tv := val\n\t\t_ = v\n\t}\n\n\treturn \"\"\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/parent/example.go",
		"package parent\n\nfunc Example() {\n\ts := \"status\"\n\tsources := []string{\"a\"}\n\n\tfor _, src := range sources {\n\t\t_ = s + src\n\t}\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/sentinel/sentinel.go",
		"package sentinel\n\nimport \"fmt\"\n\nvar ErrQuit = fmt.Errorf(\"quit\")\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/caller/caller.go",
		"package caller\n\nimport (\n\t\"errors\"\n\t\"testmodule/pkg/sentinel\"\n)\n\nfunc Check(e error) bool {\n\treturn errors.Is(e, sentinel.ErrQuit)\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/tagged/tagged.go",
		"//go:build ignore\n\npackage tagged\n\nimport (\n\t\"errors\"\n\t\"testmodule/pkg/sentinel\"\n)\n\nfunc Handle(e error) bool {\n\treturn errors.Is(e, sentinel.ErrQuit)\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/errs/example.go",
		"package errs\n\nimport \"fmt\"\n\nfunc Example() {\n\te := fmt.Errorf(\"first\")\n\terr := fmt.Errorf(\"second\")\n\t_ = e\n\t_ = err\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/errs/triple.go",
		"package errs\n\nimport \"fmt\"\n\nfunc Triple() {\n\te := fmt.Errorf(\"first\")\n\tf := fmt.Errorf(\"second\")\n\terr := fmt.Errorf(\"third\")\n\t_ = e\n\t_ = f\n\t_ = err\n}\n",
	)

	return directory
}
