package gofix

import (
	"github.com/funtimecoding/go-library/pkg/assert"
	"github.com/funtimecoding/go-library/pkg/constant"
	"github.com/funtimecoding/go-library/pkg/lint/analyzer/testutil"
	"github.com/funtimecoding/go-library/pkg/lint/output"
	"path/filepath"
	"testing"
)

func TestImportAliasFix(t *testing.T) {
	directory := writeImportAliasTestModule(t)
	r := output.NewResultsWithDirectory(directory)
	runImportAliasFixWithDirectory([]string{"./..."}, directory, false, r)
	t.Run(
		"SuperfluousAlias",
		func(t *testing.T) {
			assert.String(
				t,
				"package example\n\nimport \"testmodule/pkg/helper\"\n\nfunc UseHelper() string {\n\treturn helper.Value()\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "superfluous.go"),
				),
			)
		},
	)
	t.Run(
		"UnnecessaryRename",
		func(t *testing.T) {
			assert.String(
				t,
				"package example\n\nimport \"testmodule/pkg/helper\"\n\nfunc UseRenamed() string {\n\treturn helper.Value()\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "unnecessary_rename.go"),
				),
			)
		},
	)
	t.Run(
		"CollisionKept",
		func(t *testing.T) {
			assert.String(
				t,
				"package example\n\nimport h \"testmodule/pkg/helper\"\n\nfunc UseCollision() string {\n\thelper := \"local\"\n\n\treturn helper + h.Value()\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "collision.go"),
				),
			)
		},
	)
	t.Run(
		"ImportCollisionKept",
		func(t *testing.T) {
			assert.String(
				t,
				"package example\n\nimport (\n\th \"testmodule/pkg/helper\"\n\t\"testmodule/pkg/other/helper\"\n)\n\nfunc UseBoth() string {\n\treturn h.Value() + helper.Extra()\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"import_collision.go",
					),
				),
			)
		},
	)
	t.Run(
		"GeneratedUntouched",
		func(t *testing.T) {
			assert.String(
				t,
				"// Code generated by tool DO NOT EDIT.\n\npackage example\n\nimport h \"testmodule/pkg/helper\"\n\nfunc Generated() string {\n\treturn h.Value()\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, constant.GeneratedFile),
				),
			)
		},
	)
	t.Run(
		"DifferentDeclaredName",
		func(t *testing.T) {
			assert.String(
				t,
				"package example\n\nimport \"testmodule/pkg/util-stuff\"\n\nfunc UseDifferent() string {\n\treturn util.Format()\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "different_name.go"),
				),
			)
		},
	)
	t.Run(
		"BlankImportUntouched",
		func(t *testing.T) {
			assert.String(
				t,
				"package example\n\nimport _ \"testmodule/pkg/helper\"\n\nfunc BlankImport() {}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "blank_import.go"),
				),
			)
		},
	)
	t.Run(
		"MultipleAliasedSameName",
		func(t *testing.T) {
			assert.String(
				t,
				"package example\n\nimport (\n\ta \"testmodule/pkg/alpha/constant\"\n\tb \"testmodule/pkg/beta/constant\"\n)\n\nfunc UseMultiple() string {\n\treturn a.One() + b.Two()\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"multiple_same_name.go",
					),
				),
			)
		},
	)
	t.Run(
		"StructFieldNoCollision",
		func(t *testing.T) {
			assert.String(
				t,
				"package example\n\nimport \"testmodule/pkg/helper\"\n\ntype Thing struct {\n\thelper string\n}\n\nfunc UseThing() string {\n\treturn helper.Value()\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"struct_field.go",
					),
				),
			)
		},
	)
	t.Run(
		"ResultEntries",
		func(t *testing.T) {
			applied := filterApplied(r.Entries)
			blocked := filterBlocked(r.Entries)
			assert.Integer(t, 4, len(applied))
			assertResult(
				t,
				applied,
				"superfluous.go",
				"de-aliased helper (redundant)",
			)
			assertResult(
				t,
				applied,
				"unnecessary_rename.go",
				"de-aliased h → helper",
			)
			assertResult(
				t,
				applied,
				"different_name.go",
				"de-aliased u → util",
			)
			assertResult(
				t,
				applied,
				"struct_field.go",
				"de-aliased h → helper",
			)
			assert.Integer(t, 1, len(blocked))
			assertResult(
				t,
				blocked,
				"collision.go",
				"cannot de-alias h → helper (local collision with \"helper\")",
			)
		},
	)
}

func writeImportAliasTestModule(t *testing.T) string {
	t.Helper()
	directory := t.TempDir()
	testutil.WriteFile(
		t,
		directory,
		"go.mod",
		"module testmodule\n\ngo 1.22\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/helper/helper.go",
		"package helper\n\nfunc Value() string { return \"hello\" }\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/other/helper/helper.go",
		"package helper\n\nfunc Extra() string { return \"extra\" }\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/util-stuff/util.go",
		"package util\n\nfunc Format() string { return \"formatted\" }\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"superfluous.go",
		"package example\n\nimport helper \"testmodule/pkg/helper\"\n\nfunc UseHelper() string {\n\treturn helper.Value()\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"unnecessary_rename.go",
		"package example\n\nimport h \"testmodule/pkg/helper\"\n\nfunc UseRenamed() string {\n\treturn h.Value()\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"collision.go",
		"package example\n\nimport h \"testmodule/pkg/helper\"\n\nfunc UseCollision() string {\n\thelper := \"local\"\n\n\treturn helper + h.Value()\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"import_collision.go",
		"package example\n\nimport (\n\th \"testmodule/pkg/helper\"\n\t\"testmodule/pkg/other/helper\"\n)\n\nfunc UseBoth() string {\n\treturn h.Value() + helper.Extra()\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		constant.GeneratedFile,
		"// Code generated by tool DO NOT EDIT.\n\npackage example\n\nimport h \"testmodule/pkg/helper\"\n\nfunc Generated() string {\n\treturn h.Value()\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"different_name.go",
		"package example\n\nimport u \"testmodule/pkg/util-stuff\"\n\nfunc UseDifferent() string {\n\treturn u.Format()\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"blank_import.go",
		"package example\n\nimport _ \"testmodule/pkg/helper\"\n\nfunc BlankImport() {}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/alpha/constant/constant.go",
		"package constant\n\nfunc One() string { return \"one\" }\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"pkg/beta/constant/constant.go",
		"package constant\n\nfunc Two() string { return \"two\" }\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"multiple_same_name.go",
		"package example\n\nimport (\n\ta \"testmodule/pkg/alpha/constant\"\n\tb \"testmodule/pkg/beta/constant\"\n)\n\nfunc UseMultiple() string {\n\treturn a.One() + b.Two()\n}\n",
	)
	testutil.WriteFile(
		t,
		directory,
		"struct_field.go",
		"package example\n\nimport h \"testmodule/pkg/helper\"\n\ntype Thing struct {\n\thelper string\n}\n\nfunc UseThing() string {\n\treturn h.Value()\n}\n",
	)

	return directory
}
