package gofix

var whitelist = map[string]bool{
	// Single letters (always acceptable)
	"a": true, "b": true, "c": true, "d": true, "e": true,
	"f": true, "g": true, "h": true, "i": true, "j": true,
	"k": true, "l": true, "m": true, "n": true, "o": true,
	"p": true, "q": true, "r": true, "s": true, "t": true,
	"u": true, "v": true, "w": true, "x": true, "y": true,
	"z": true,

	// Go keywords and builtins
	"any": true, "bool": true, "byte": true, "cap": true,
	"close": true, "copy": true, "delete": true, "error": true,
	"false": true, "float32": true, "float64": true, "int": true,
	"int8": true, "int16": true, "int32": true, "int64": true,
	"len": true, "make": true, "map": true, "max": true,
	"min": true, "new": true, "nil": true, "panic": true,
	"print": true, "println": true, "real": true, "rune": true,
	"string": true, "true": true, "uint": true, "uint8": true,
	"uint16": true, "uint32": true, "uint64": true,

	// Already banned (handled by naming analyzer)
	"url": true, "mcp": true, "dir": true, "dirs": true,
	"tx": true, "ctx": true, "param": true, "msg": true,
	"req": true, "doc": true, "pos": true, "buf": true,
	"ptr": true, "addr": true, "ref": true, "nav": true,
	"prev": true, "decl": true, "yaml": true, "xml": true,
	"html": true, "json": true, "config": true, "cfg": true,
	"llm": true, "tmp": true, "href": true, "def": true,
	"concat": true, "obj": true, "stmt": true, "var": true,
	"const": true, "handler": true, "data": true, "info": true,
	"func": true, "sig": true, "pkg": true, "err": true,
	"val": true, "args": true, "opt": true, "cols": true,
	"loc": true, "dep": true,

	// Common English words used in identifiers
	"accept": true, "access": true, "account": true, "action": true,
	"active": true, "actual": true, "add": true, "address": true,
	"after": true, "alert": true, "all": true, "allow": true,
	"already": true, "alternative": true, "always": true,
	"annotation": true, "api": true, "append": true, "applicable": true,
	"application": true, "apply": true, "archive": true, "argument": true,
	"assert": true, "asset": true, "assign": true, "assignment": true,
	"at": true, "attribute": true, "authenticate": true,
	"authentication": true, "authorization": true, "authorize": true,
	"available": true,
	"back":      true, "backup": true, "ban": true, "banned": true,
	"bar": true, "base": true, "basic": true, "batch": true,
	"before": true, "begin": true, "below": true, "between": true,
	"binary": true, "bind": true, "blank": true, "block": true,
	"body": true, "bold": true, "boolean": true, "boot": true,
	"both": true, "bottom": true, "boundary": true, "branch": true,
	"break": true, "bridge": true, "brief": true, "broadcast": true,
	"browser": true, "bucket": true, "buffer": true, "bug": true,
	"build": true, "builder": true, "builtin": true, "bump": true,
	"bundle": true, "bus": true, "button": true, "by": true,
	"cache": true, "call": true, "callback": true, "cancel": true,
	"candidate": true, "capture": true, "case": true, "cast": true,
	"category": true, "cell": true, "certificate": true, "chain": true,
	"change": true, "channel": true, "check": true, "checker": true,
	"child": true, "chunk": true, "cipher": true, "class": true,
	"clean": true, "clear": true, "click": true, "client": true,
	"clone": true, "cluster": true, "code": true, "collect": true,
	"collection": true, "color": true, "column": true, "combine": true,
	"comma": true, "command": true, "comment": true, "commit": true,
	"common": true, "compact": true, "compare": true, "compile": true,
	"complete": true, "component": true, "compose": true,
	"composite": true, "compress": true, "compute": true,
	"concatenate": true, "concern": true, "condition": true,
	"configuration": true, "configure": true, "confirm": true,
	"conflict": true, "connect": true, "connection": true,
	"console": true, "constant": true, "constraint": true,
	"construct": true, "constructor": true, "consume": true,
	"consumer": true, "contact": true, "contain": true,
	"container": true, "content": true, "context": true,
	"continue": true, "control": true, "controller": true,
	"convert": true, "cookie": true, "coordinate": true,
	"core": true, "correct": true, "count": true, "counter": true,
	"create": true, "credential": true, "critical": true,
	"cross": true, "current": true, "cursor": true, "custom": true,
	"cycle":  true,
	"daemon": true, "daily": true, "dashboard": true, "database": true,
	"date": true, "day": true, "dead": true, "debug": true,
	"decimal": true, "declaration": true, "declare": true,
	"decode": true, "decoder": true, "decrypt": true, "deep": true,
	"default": true, "defer": true, "define": true, "definition": true,
	"delay": true, "delegate": true, "delivery": true, "delta": true,
	"deny": true, "deploy": true, "deployment": true, "depth": true,
	"derive": true, "describe": true, "description": true,
	"deserialize": true, "design": true, "desired": true,
	"destination": true, "detail": true, "detect": true,
	"determine": true, "device": true, "dial": true, "diff": true,
	"digest": true, "digit": true, "direct": true, "direction": true,
	"directories": true, "directory": true, "disable": true,
	"discard": true, "disconnect": true, "discover": true,
	"discovery": true, "disk": true, "dispatch": true, "display": true,
	"distinct": true, "document": true, "domain": true, "done": true,
	"dot": true, "double": true, "down": true, "download": true,
	"drain": true, "drive": true, "driver": true, "drop": true,
	"dry": true, "dump": true, "duplicate": true, "duration": true,
	"dynamic": true,
	"each":    true, "edge": true, "edit": true, "editor": true,
	"effect": true, "element": true, "else": true, "embed": true,
	"emit": true, "empty": true, "enable": true, "encode": true,
	"encoder": true, "encrypt": true, "end": true, "endpoint": true,
	"engine": true, "ensure": true, "enter": true, "entire": true,
	"entity": true, "entry": true, "enum": true, "enumerate": true,
	"environment": true, "equal": true, "escape": true, "event": true,
	"every": true, "exact": true, "example": true, "except": true,
	"exception": true, "exchange": true, "exclude": true,
	"execute": true, "execution": true, "exempt": true,
	"exist": true, "exists": true, "exit": true, "expand": true,
	"expect": true, "expected": true, "experiment": true,
	"expire": true, "explicit": true, "export": true, "exported": true,
	"expression": true, "extend": true, "extension": true,
	"external": true, "extra": true, "extract": true, "extraneous": true,
	"face": true, "fact": true, "factory": true, "fail": true,
	"failed": true, "failure": true, "fallback": true, "family": true,
	"fatal": true, "feature": true, "fetch": true, "field": true,
	"file": true, "fill": true, "filter": true, "final": true,
	"finalize": true, "find": true, "fingerprint": true,
	"finish": true, "fire": true, "firing": true, "first": true,
	"fix": true, "fixed": true, "flag": true, "flagged": true,
	"flat": true, "float": true, "floor": true, "flow": true,
	"flush": true, "folder": true, "follow": true, "for": true,
	"force": true, "fork": true, "form": true, "format": true,
	"formatter": true, "forward": true, "found": true, "frame": true,
	"free": true, "frequency": true, "fresh": true, "from": true,
	"front": true, "full": true, "function": true,
	"gain": true, "gather": true, "generate": true, "generated": true,
	"generator": true, "generic": true, "get": true, "git": true,
	"give": true, "global": true, "go": true, "goal": true,
	"golden": true, "good": true, "grace": true, "graceful": true,
	"grant": true, "graph": true, "green": true, "grep": true,
	"group": true, "grow": true, "guard": true, "guess": true,
	"guide": true,
	"half":  true, "handle": true, "hard": true, "has": true,
	"hash": true, "have": true, "head": true, "header": true,
	"health": true, "heap": true, "height": true, "help": true,
	"helper": true, "here": true, "hidden": true, "hierarchy": true,
	"high": true, "hint": true, "history": true, "hit": true,
	"hold": true, "home": true, "hook": true, "host": true,
	"hostname": true, "hour": true, "human": true,
	"icon": true, "id": true, "identifier": true, "identity": true,
	"idle": true, "if": true, "ignore": true, "image": true,
	"immediate": true, "implement": true, "implementation": true,
	"import": true, "in": true, "inactive": true, "include": true,
	"increment": true, "indent": true, "index": true, "indicate": true,
	"indicator": true, "indirect": true, "inherit": true, "init": true,
	"initial": true, "initialize": true, "inject": true, "inline": true,
	"inner": true, "input": true, "insert": true, "inside": true,
	"inspect": true, "inspector": true, "install": true,
	"instance": true, "integer": true, "integer64": true,
	"interface": true, "internal": true, "interpolate": true,
	"interval": true, "into": true, "invalid": true, "inverse": true,
	"invoke": true, "ip": true, "is": true, "issue": true,
	"item": true, "iterate": true, "iteration": true, "iterator": true,
	"job": true, "join": true, "journal": true, "jump": true,
	"just": true,
	"keep": true, "key": true, "keyword": true, "kill": true,
	"kind": true, "known": true,
	"label": true, "lang": true, "language": true, "last": true,
	"late": true, "latest": true, "launch": true, "layer": true,
	"lazy": true, "lead": true, "leaf": true, "leak": true,
	"left": true, "length": true, "less": true, "level": true,
	"library": true, "license": true, "life": true, "lifecycle": true,
	"limit": true, "line": true, "link": true, "linker": true,
	"list": true, "listen": true, "listener": true, "literal": true,
	"live": true, "load": true, "loader": true, "local": true,
	"locate": true, "location": true, "locator": true, "lock": true,
	"log": true, "logger": true, "logic": true, "login": true,
	"long": true, "look": true, "lookup": true, "loop": true,
	"lose": true, "loss": true, "lost": true, "low": true,
	"lower":   true,
	"machine": true, "macro": true, "main": true, "maintain": true,
	"maintenance": true, "major": true, "manage": true,
	"manager": true, "manifest": true, "manual": true, "many": true,
	"mark": true, "marker": true, "markup": true, "marshal": true,
	"mask": true, "master": true, "match": true, "matcher": true,
	"material": true, "math": true, "maximum": true,
	"measure": true, "measurement": true, "media": true,
	"member": true, "memory": true, "merge": true, "message": true,
	"meta": true, "metadata": true, "method": true, "metric": true,
	"middle": true, "migrate": true, "migration": true,
	"mime": true, "minimum": true, "minor": true, "minute": true,
	"mirror": true, "miss": true, "missing": true, "mix": true,
	"mock": true, "mode": true, "model": true, "modify": true,
	"module": true, "monitor": true, "month": true, "more": true,
	"mount": true, "move": true, "multi": true, "multiple": true,
	"must": true, "mutable": true, "mute": true, "mutex": true,
	"name": true, "named": true, "namespace": true, "native": true,
	"natural": true, "navigation": true, "need": true, "negative": true,
	"nest": true, "nested": true, "net": true, "network": true,
	"never": true, "next": true, "no": true, "node": true,
	"none": true, "normal": true, "normalize": true, "not": true,
	"notation": true, "note": true, "nothing": true, "notice": true,
	"notification": true, "notifier": true, "notify": true,
	"now": true, "null": true, "number": true,
	"object": true, "observe": true, "observer": true, "obtain": true,
	"of": true, "off": true, "offset": true, "ok": true, "old": true,
	"on": true, "once": true, "one": true, "only": true, "open": true,
	"operate": true, "operation": true, "operator": true,
	"option": true, "optional": true, "or": true, "order": true,
	"origin": true, "original": true, "other": true, "out": true,
	"outer": true, "output": true, "outside": true, "over": true,
	"overflow": true, "overlap": true, "override": true, "own": true,
	"owned": true, "owner": true,
	"pack": true, "package": true, "pad": true, "padding": true,
	"page": true, "pair": true, "parallel": true,
	"parameter": true, "parent": true, "parse": true, "parser": true,
	"part": true, "partial": true, "partition": true, "pass": true,
	"password": true, "past": true, "patch": true, "path": true,
	"pattern": true, "pause": true, "payload": true, "peer": true,
	"pending": true, "percent": true, "perform": true,
	"performance": true, "period": true, "permanent": true,
	"permission": true, "persist": true, "phase": true, "pick": true,
	"pin": true, "ping": true, "pipe": true, "pipeline": true,
	"place": true, "placeholder": true, "plain": true, "plan": true,
	"platform": true, "play": true, "plugin": true, "plus": true,
	"point": true, "pointer": true, "policy": true, "poll": true,
	"poller": true, "pool": true, "pop": true, "populate": true,
	"port": true, "position": true, "positive": true, "post": true,
	"power": true, "practice": true, "pre": true, "predict": true,
	"prefix": true, "prepare": true, "present": true, "preserve": true,
	"preset": true, "press": true, "pretty": true, "primary": true,
	"primitive": true, "priority": true, "private": true,
	"probe": true, "problem": true, "procedure": true, "process": true,
	"produce": true, "producer": true, "product": true,
	"production": true, "profile": true, "program": true,
	"progress": true, "project": true, "promise": true, "prompt": true,
	"propagate": true, "property": true, "protect": true,
	"protocol": true, "provide": true, "provider": true, "proxy": true,
	"public": true, "publish": true, "pull": true, "purge": true,
	"push": true, "put": true,
	"qualifier": true, "quality": true, "query": true, "queue": true,
	"quick": true, "quiet": true, "quit": true, "quote": true,
	"race": true, "random": true, "range": true, "rank": true,
	"rate": true, "raw": true, "re": true, "reach": true, "read": true,
	"reader": true, "ready": true, "receive": true, "receiver": true,
	"recent": true, "recognize": true, "record": true, "recover": true,
	"recovery": true, "recursive": true, "redirect": true,
	"reduce": true, "reference": true, "reflect": true, "refresh": true,
	"region": true, "register": true, "registry": true, "reject": true,
	"related": true, "relation": true, "relative": true,
	"release": true, "reload": true, "remain": true, "remaining": true,
	"remote": true, "remove": true, "rename": true, "render": true,
	"repeat": true, "replace": true, "replacement": true,
	"replica": true, "replicate": true, "report": true,
	"reporter": true, "repository": true, "represent": true,
	"request": true, "require": true, "required": true, "reset": true,
	"resize": true, "resolve": true, "resolved": true,
	"resource": true, "response": true, "rest": true, "restart": true,
	"restore": true, "restrict": true, "result": true, "resume": true,
	"retain": true, "retry": true, "return": true, "reverse": true,
	"revert": true, "review": true, "revision": true, "revoke": true,
	"right": true, "ring": true, "role": true, "roll": true,
	"rollback": true, "root": true, "rotate": true, "round": true,
	"route": true, "router": true, "row": true, "rule": true,
	"run": true, "runner": true, "runtime": true,
	"safe": true, "salt": true, "sample": true, "sandbox": true,
	"sanitize": true, "save": true, "scale": true, "scan": true,
	"scanner": true, "schedule": true, "scheduler": true,
	"schema": true, "scheme": true, "scope": true, "score": true,
	"screen": true, "script": true, "scroll": true, "search": true,
	"second": true, "secret": true, "section": true, "secure": true,
	"security": true, "seed": true, "seek": true, "segment": true,
	"select": true, "self": true, "send": true, "sender": true,
	"sensitive": true, "separator": true, "sequence": true,
	"serial": true, "serialize": true, "series": true, "serve": true,
	"server": true, "service": true, "session": true, "set": true,
	"setting": true, "setup": true, "severity": true, "shadow": true,
	"shape": true, "share": true, "shared": true, "shell": true,
	"shift": true, "short": true, "should": true, "show": true,
	"shutdown": true, "side": true, "sign": true, "signal": true,
	"signature": true, "silent": true, "simple": true, "simulate": true,
	"since": true, "single": true, "sink": true, "site": true,
	"size": true, "skip": true, "slice": true, "slow": true,
	"slug": true, "small": true, "snapshot": true, "socket": true,
	"soft": true, "some": true, "sort": true, "sorted": true,
	"source": true, "space": true, "span": true, "spawn": true,
	"special": true, "specification": true, "specific": true,
	"split": true, "stable": true, "stack": true, "stage": true,
	"stale": true, "standalone": true, "standard": true, "start": true,
	"state": true, "statement": true, "static": true, "statistics": true,
	"status": true, "stay": true, "step": true, "sticky": true,
	"still": true, "stop": true, "storage": true, "store": true,
	"stray": true, "stream": true, "strict": true, "strike": true,
	"strip": true, "strong": true, "struct": true, "structure": true,
	"stub": true, "style": true, "sub": true, "subject": true,
	"submit": true, "subscribe": true, "subscription": true,
	"success": true, "suffix": true, "suggest": true,
	"suggestion": true, "suite": true, "sum": true, "summary": true,
	"super": true, "support": true, "suppress": true,
	"suppressed": true, "surface": true, "swap": true, "switch": true,
	"symbol": true, "sync": true, "syntax": true, "system": true,
	"tab": true, "table": true, "tag": true, "tail": true,
	"take": true, "target": true, "task": true, "team": true,
	"template": true, "temporary": true, "tenant": true, "term": true,
	"terminal": true, "terminate": true, "test": true, "text": true,
	"than": true, "that": true, "the": true, "then": true,
	"there": true, "this": true, "thread": true, "threshold": true,
	"through": true, "throw": true, "tick": true, "ticker": true,
	"ticket": true, "time": true, "timeout": true, "timer": true,
	"timestamp": true, "title": true, "to": true, "toggle": true,
	"token": true, "tolerance": true, "tool": true, "top": true,
	"topic": true, "total": true, "touch": true, "trace": true,
	"track": true, "tracker": true, "traffic": true, "trail": true,
	"trailing": true, "trait": true, "transaction": true,
	"transfer": true, "transform": true, "transition": true,
	"translate": true, "transport": true, "traverse": true,
	"tree": true, "trend": true, "trigger": true, "trim": true,
	"trust": true, "try": true, "tunnel": true, "turn": true,
	"type": true, "typed": true,
	"unable": true, "unchanged": true, "under": true,
	"underlying": true, "undo": true, "unexpected": true,
	"unhandled": true, "unicode": true, "unified": true,
	"unique": true, "unit": true, "universal": true, "unknown": true,
	"unless": true, "unlike": true, "unlock": true, "unmarshal": true,
	"unpack": true, "unset": true, "until": true, "unused": true,
	"up": true, "update": true, "upgrade": true, "upload": true,
	"upper": true, "upstream": true, "uri": true, "usage": true,
	"use": true, "used": true, "user": true, "username": true,
	"using": true, "usual": true, "utility": true,
	"valid": true, "validate": true, "validation": true,
	"validator": true, "value": true, "variable": true, "vendor": true,
	"verbose": true, "verify": true, "version": true, "vertical": true,
	"via": true, "view": true, "virtual": true, "visible": true,
	"visit": true, "volume": true, "vulnerability": true,
	"wait": true, "walk": true, "want": true, "warm": true,
	"warn": true, "warning": true, "watch": true, "watcher": true,
	"web": true, "webhook": true, "week": true, "weight": true,
	"when": true, "where": true, "which": true, "while": true,
	"white": true, "whole": true, "wide": true, "widget": true,
	"width": true, "wiki": true, "wild": true, "window": true,
	"with": true, "within": true, "without": true, "word": true,
	"work": true, "worker": true, "working": true, "workspace": true,
	"world": true, "wrap": true, "wrapper": true, "write": true,
	"writer": true, "wrong": true,
	"year": true, "yield": true,
	"zero": true, "zone": true,

	// Domain words and proper nouns from survey
	"sentry": true, "prometheus": true, "jira": true, "gitlab": true,
	"github": true, "kaos": true, "kestra": true, "grafana": true,
	"kubernetes": true, "proxmox": true, "opsgenie": true,
	"jenkins": true, "renovate": true, "trivy": true, "ceph": true,
	"consul": true, "vault": true, "ansible": true, "terraform": true,
	"discord": true, "slack": true, "htmx": true, "alpine": true,
	"debian": true, "darwin": true, "linux": true, "zulu": true,
	"gaia": true, "kevt": true,

	// Short words from survey (not already in common English words above)
	"age": true, "ago": true, "aid": true, "aim": true, "air": true,
	"aka": true, "arc": true, "arm": true, "ask": true, "ate": true,
	"auto": true, "bay": true, "bid": true,
	"big": true, "bin": true, "bit": true, "box": true,
	"brew": true, "bulk": true, "busy": true,
	"cask": true, "chat": true, "cite": true, "clan": true,
	"cron": true, "cup": true, "cut": true, "dam": true,
	"dash": true, "desk": true, "did": true,
	"dig": true, "dim": true, "dip": true, "dns": true,
	"duo": true, "dye": true, "ear": true,
	"eat": true, "echo": true, "ego": true, "era": true,
	"eta": true, "eve": true, "eye": true, "fan": true,
	"far": true, "fat": true, "few": true, "fig": true,
	"fin": true, "fit": true, "fly": true,
	"fog": true, "fox": true, "fun": true, "fur": true,
	"gap": true, "gas": true, "gem": true, "gin": true,
	"gnu": true, "got": true, "gum": true, "gun": true,
	"gut": true, "guy": true, "gym": true,
	"had": true, "ham": true, "hat": true, "hen": true,
	"hex": true, "hip": true, "hog": true, "hop": true,
	"hot": true, "hub": true, "hue": true, "hug": true,
	"hut": true,
	"ice": true, "ill": true, "ink": true, "inn": true,
	"ion": true, "ire": true, "ivy": true,
	"jam": true, "jar": true, "jaw": true, "jet": true,
	"jog": true, "joy": true, "jug": true,
	"kin": true, "kit": true,
	"lab": true, "lag": true, "lap": true, "law": true,
	"lay": true, "led": true, "leg": true, "let": true,
	"lid": true, "lie": true, "lip": true, "lit": true,
	"lot": true,
	"mad": true, "mat": true, "mid": true,
	"mob": true, "mod": true, "mud": true, "mug": true,
	"nap": true, "nib": true, "nod": true,
	"nor": true, "nut": true,
	"oak": true, "oat": true, "odd": true, "ode": true,
	"oil": true, "ooze": true, "orb": true, "ore": true, "our": true,
	"owe": true, "owl": true,
	"pan": true, "paw": true, "pay": true,
	"peg": true, "pen": true, "per": true, "pet": true,
	"pie": true, "pig": true, "pit": true,
	"pod": true, "pot": true, "pub": true, "pun": true,
	"rack": true, "rag": true, "ram": true, "ran": true,
	"rap": true, "rat": true, "ray": true,
	"red": true, "rig": true, "rim": true, "rip": true,
	"rod": true, "rot": true, "rub": true,
	"rug": true, "rum": true, "rut": true,
	"sad": true, "sat": true, "saw": true, "say": true,
	"sea": true, "sir": true, "sit": true, "six": true,
	"ski": true, "sky": true, "sly": true, "sob": true,
	"sod": true, "sol": true, "son": true, "sow": true,
	"spa": true, "spy": true, "ssh": true, "sue": true,
	"sun": true,
	"tan": true, "tap": true,
	"tar": true, "tax": true, "tea": true, "ten": true,
	"tie": true, "tin": true, "tip": true,
	"toe": true, "ton": true, "too": true,
	"tow": true, "toy": true, "tub": true,
	"tug": true, "two": true,
	"urn": true,
	"van": true, "vat": true, "vet": true,
	"vim": true, "vow": true,
	"wag": true, "war": true, "was": true, "wax": true,
	"way": true, "wed": true, "wet": true,
	"who": true, "why": true, "wig": true, "win": true,
	"wit": true, "woe": true, "wok": true, "won": true,
	"woo": true, "wow": true,
	"yam": true, "yap": true, "yaw": true, "yep": true,
	"yes": true, "yet": true, "yew": true, "yin": true,
	"yip": true,
	"zap": true, "zen": true, "zig": true, "zip": true,
	"zoo": true,

	// Common plural/verb forms from survey
	"alerts": true, "bytes": true, "changes": true, "checks": true,
	"columns": true, "concerns": true, "contains": true,
	"days": true, "entries": true, "errors": true, "events": true,
	"fields": true, "files": true, "groups": true, "issues": true,
	"items": true, "jobs": true, "keys": true, "labels": true,
	"lines": true, "links": true, "logs": true, "members": true,
	"messages": true, "minutes": true, "names": true, "nodes": true,
	"notes": true, "pages": true, "parameters": true, "parts": true,
	"paths": true, "records": true, "requests": true, "results": true,
	"rows": true, "rules": true, "runs": true, "secrets": true,
	"services": true, "settings": true, "spans": true, "steps": true,
	"strings": true, "tags": true, "tasks": true, "tests": true,
	"tokens": true, "tools": true, "types": true, "users": true,
	"values": true, "workers": true,
	"allowed": true, "called": true, "changed": true, "checked": true,
	"closed": true, "configured": true, "connected": true,
	"created": true, "defined": true, "deleted": true, "enabled": true,
	"enriched": true, "filtered": true, "formatted": true,
	"grouped": true, "handled": true,
	"initialized": true, "installed": true, "loaded": true,
	"logged": true, "mapped": true, "matched": true, "merged": true,
	"modified": true, "mounted": true, "opened": true,
	"ordered": true, "parsed": true, "passed": true,
	"printed": true, "processed": true, "published": true,
	"received": true, "registered": true, "removed": true,
	"replaced": true, "returned": true,
	"running": true, "saved": true, "seen": true, "selected": true,
	"signed": true, "started": true, "stopped": true,
	"stored": true, "stripped": true, "trimmed": true,
	"updated": true, "uploaded": true, "validated": true,

	// Technical terms from survey
	"amd64": true, "architecture": true,
	"cgroup": true, "cidr": true, "cname": true, "cors": true,
	"cpu": true, "cve": true, "dbname": true, "dhcp": true,
	"emoji": true, "favicon": true, "fqdn": true,
	"glob": true, "gpu": true, "grpc": true, "gzip": true,
	"http": true, "https": true, "icmp": true, "imap": true,
	"ioctl": true, "ipv4": true, "ipv6": true, "iso": true,
	"jwt": true, "ldap": true, "loki": true, "mac": true,
	"mailto": true, "mqtt": true, "nginx": true, "noop": true,
	"oauth": true, "okay": true, "pem": true, "pid": true,
	"regex": true, "rfc": true, "rgba": true, "rsa": true,
	"rtsp": true, "smtp": true, "snmp": true, "sql": true,
	"ssl": true, "sudo": true, "svg": true, "tcp": true,
	"tls": true, "toml": true, "ttl": true, "udp": true,
	"uid": true, "unix": true, "uuid": true, "vlan": true,
	"vmid": true, "vnc": true, "vpn": true, "wss": true,

	// Project-specific identifiers from survey
	"enrich": true, "hx": true, "osc8": true,
	"cellar": true, "guild": true, "physical": true, "tiny": true,
	"nano": true, "kilo": true, "mike": true, "fish": true,
	"alfa": true, "bravo": true, "charlie": true,
	"papa": true, "five": true, "mine": true, "star": true,
	"ones": true, "andy": true, "xray": true,

	// Version identifiers
	"v1": true, "v2": true, "v3": true, "v4": true,
}
