package example

import (
	"context"
	"fmt"
	"github.com/funtimecoding/go-library/pkg/mattermost"
	"github.com/funtimecoding/go-library/pkg/strings/join"
	"github.com/funtimecoding/go-library/pkg/system"
	"github.com/funtimecoding/go-library/pkg/text/multi_line"
	"github.com/funtimecoding/go-library/pkg/web"
	"github.com/funtimecoding/go-library/pkg/web/request_context"
	"github.com/mattermost/mattermost-server/v6/model"
	"net/http"
)

func Dialog() {
	w := http.NewServeMux()
	w.HandleFunc(
		"/dialog",
		func(
			w http.ResponseWriter,
			e *http.Request,
		) {
			c := request_context.New(w, e)
			c.SetLastLocation()
			l := multi_line.New()
			l.Format("Raw query: %s", c.Request().URL.RawQuery)

			for k, v := range c.Request().Header {
				l.Format("Header: %s=%s", k, join.Comma(v))
			}

			l.Format("Body: %s", c.Body())
			c.WriteOkay("Dialog request received.")

			fmt.Println("Dialog request:")
			fmt.Println(l.Render())
		},
	)
	s := web.ListenAsynchronous(w)
	m := mattermost.NewEnvironment()

	if true {
		h := m.DefaultChannel()
		p := &model.Post{
			ChannelId: h.Id,
			Message:   "Some message with buttons",
		}
		attachments := []map[string]any{
			{
				"color": "#36a64f",
				"fields": []map[string]any{
					{
						"title": "Current Version",
						"value": "v2.1.0",
						"short": true,
					},
					{
						"title": "Target Version",
						"value": "v2.2.1",
						"short": true,
					},
				},
				"actions": []map[string]any{
					{
						"id":    "update_yes",
						"name":  "✅ Yes, Update",
						"type":  "button",
						"style": "primary",
						"integration": map[string]any{
							"url": "http://localhost:8080/dialog",
							"context": map[string]any{
								"action":  "update_server",
								"server":  "prod-web-01",
								"version": "v2.2.1",
							},
						},
					},
					{
						"id":    "update_cancel",
						"name":  "❌ Cancel",
						"type":  "button",
						"style": "danger",
						"integration": map[string]any{
							"url": "http://localhost:8080/dialog",
							"context": map[string]any{
								"action": "cancel_update",
							},
						},
					},
				},
			},
		}
		p.SetProps(map[string]any{"attachments": attachments})
		m.Post(p)
	}

	if false {
		elements := []model.DialogElement{
			{
				DisplayName: "",
				Name:        "",
				Type:        "",
				SubType:     "",
				Default:     "",
				Placeholder: "",
				HelpText:    "",
				Optional:    false,
				MinLength:   0,
				MaxLength:   0,
				DataSource:  "",
				Options:     nil,
			},
		}
		fmt.Printf("Dialog elements: %d\n", len(elements))
	}

	if false {
		m.OpenDialog(
			model.OpenDialogRequest{
				TriggerId: "", // Generated by server
				URL:       "http://localhost:8080/dialog",
				Dialog: model.Dialog{
					CallbackId:       "myOwnId", // Probably used to identify the dialog when the callback arrives
					Title:            "Maximum 24 characters",
					IntroductionText: "Markdown formatted text",
					IconURL:          "",    // Optional
					Elements:         nil,   // Should be enough to have a submit and cancel button
					SubmitLabel:      "",    // Optional
					NotifyOnCancel:   false, // Optional
					State:            "",    // Optional
				},
			},
		)
	}

	if false {
		m.SubmitDialog(
			model.SubmitDialogRequest{
				Type:       "",
				URL:        "",
				CallbackId: "",
				State:      "",
				UserId:     "",
				ChannelId:  m.DefaultChannel().Id,
				TeamId:     m.DefaultTeam().Id,
				Submission: nil,
				Cancelled:  false,
			},
		)
	}

	fmt.Println("Cancel server with Ctrl-C")
	system.KillSignalBlock()
	fmt.Println("Shutdown server")
	web.GracefulShutdown(context.Background(), s, false)
}
