package constant

const (
	Watchdog                = "Watchdog"
	KubernetesCronJobFailed = "KubernetesCronJobFailed"
)

// Entity
const (
	Backup        = "Backup"
	Battery       = "Battery"
	Cache         = "Cache"
	Certificate   = "Certificate"
	Check         = "Check"
	Clock         = "Clock"
	Cluster       = "Cluster"
	Configuration = "Configuration"
	Connection    = "Connection"
	Container     = "Container"
	DaemonSet     = "DaemonSet"
	Database      = "Database"
	Date          = "Date"
	Deadline      = "Deadline"
	Deployment    = "Deployment"
	Disk          = "Disk"
	Event         = "Event"
	Fan           = "Fan"
	Hardware      = "Hardware"
	Interface     = "Interface"
	Job           = "Job"
	Latency       = "Latency"
	Limit         = "Limit"
	Measure       = "Measure"
	Memory        = "Memory"
	MountPoint    = "MountPoint"
	Node          = "Node"
	Pod           = "Pod"
	Processor     = "Processor"
	Queue         = "Queue"
	ReplicaSet    = "ReplicaSet"
	Replication   = "Replication"
	Report        = "Report"
	Service       = "Service"
	StatefulSet   = "StatefulSet"
	System        = "System"
	Token         = "Token"
	Volume        = "Volume"
)

// Category
const (
	Bad          = "Bad"
	Behind       = "Behind"
	Big          = "Big"
	Broken       = "Broken"
	Close        = "Close"
	Corrupt      = "Corrupt"
	Disconnected = "Disconnected"
	Down         = "Down"
	Empty        = "Empty"
	Exceeded     = "Exceeded"
	Expired      = "Expired"
	Fail         = "Fail"
	Frozen       = "Frozen"
	Full         = "Full"
	High         = "High"
	Imbalance    = "Imbalance"
	Inconsistent = "Inconsistent"
	Lag          = "Lag"
	Load         = "Load"
	Low          = "Low"
	Missing      = "Missing"
	NearExceeded = "NearExceeded"
	NearExpired  = "NearExpired"
	NearFull     = "NearFull"
	Off          = "Off"
	Old          = "Old"
	OutOfMemory  = "OutOfMemory"
	OutOfSync    = "OutOfSync"
	Overload     = "Overload"
	ReadOnly     = "ReadOnly"
	Slow         = "Slow"
	Stuck        = "Stuck"
	Timeout      = "Timeout"
	Unbound      = "Unbound"
	Unhealthy    = "Unhealthy"

	Okay = "Okay"
)
