package argument

const (
	Branch     = "branch"
	Executable = "executable"
	Header     = "header"
	Host       = "host"
	Locator    = "locator"
	Main       = "main"
	Message    = "message"
	Name       = "name"
	Output     = "output"
	Owner      = "owner"
	Package    = "package"
	Password   = "password"
	Path       = "path"
	Project    = "project"
	Replace    = "replace"
	Repository = "repository"
	Tag        = "tag"
	Template   = "template"
	Token      = "token"
	User       = "user"
	Verbose    = "verbose"
	Version    = "version"
)
