package goanalyze

import (
	"github.com/funtimecoding/go-library/pkg/assert"
	"go/token"
	"os"
	"path/filepath"
	"testing"
)

func TestFixCrossPackageRename(t *testing.T) {
	directory := writeTestModule(t)
	fileSet := token.NewFileSet()
	all := load(fileSet, directory, []string{"./..."})
	violations := findViolations(all)
	edits := buildAllEdits(all, violations)
	applyEdits(fileSet, edits, directory, false)
	assert.String(
		t,
		"package types\n\nfunc DirectoryPath() string { return directoryName }\n",
		readFile(t, filepath.Join(directory, "pkg", "types", "directory_path.go")),
	)
	assert.String(
		t,
		"package types\n\nvar directoryName = \"test\"\n",
		readFile(t, filepath.Join(directory, "pkg", "types", "directory_name.go")),
	)
	assert.String(
		t,
		"package types\n\nconst StrayConstant = \"value\"\n",
		readFile(t, filepath.Join(directory, "pkg", "types", "stray_const.go")),
	)
	assert.String(
		t,
		"package consumer\n\nimport \"testmodule/pkg/types\"\n\nfunc Example() string {\n\t_ = types.StrayConstant\n\n\treturn types.DirectoryPath()\n}\n",
		readFile(t, filepath.Join(directory, "pkg", "consumer", "use.go")),
	)
}

func TestFixSkipsInterfaceMethod(t *testing.T) {
	directory := writeTestModule(t)
	fileSet := token.NewFileSet()
	all := load(fileSet, directory, []string{"./..."})
	violations := findViolations(all)
	edits := buildAllEdits(all, violations)
	applyEdits(fileSet, edits, directory, false)
	assert.String(
		t,
		"package impl\n\nimport \"testmodule/pkg/face\"\n\ntype Server struct{}\n\nfunc (s Server) Addr() string { return \"\" }\n\nvar _ face.Worker = Server{}\n",
		readFile(t, filepath.Join(directory, "pkg", "impl", "impl.go")),
	)
}

func TestFixSkipsGeneratedFile(t *testing.T) {
	directory := writeTestModule(t)
	fileSet := token.NewFileSet()
	all := load(fileSet, directory, []string{"./..."})
	violations := findViolations(all)
	edits := buildAllEdits(all, violations)
	applyEdits(fileSet, edits, directory, false)
	original := "package types\n\n// Code generated by tool DO NOT EDIT.\n\ntype ParamError struct{}\n"
	assert.String(
		t,
		original,
		readFile(t, filepath.Join(directory, "pkg", "types", "generated.go")),
	)
}

func writeTestModule(t *testing.T) string {
	t.Helper()
	directory := t.TempDir()
	writeFile(t, directory, "go.mod", "module testmodule\n\ngo 1.22\n")
	writeFile(t, directory, "pkg/types/directory_path.go",
		"package types\n\nfunc DirPath() string { return dirName }\n")
	writeFile(t, directory, "pkg/types/directory_name.go",
		"package types\n\nvar dirName = \"test\"\n")
	writeFile(t, directory, "pkg/types/stray_const.go",
		"package types\n\nconst StrayConst = \"value\"\n")
	writeFile(t, directory, "pkg/types/generated.go",
		"package types\n\n// Code generated by tool DO NOT EDIT.\n\ntype ParamError struct{}\n")
	writeFile(t, directory, "pkg/face/worker.go",
		"package face\n\ntype Worker interface {\n\tAddr() string\n}\n")
	writeFile(t, directory, "pkg/impl/impl.go",
		"package impl\n\nimport \"testmodule/pkg/face\"\n\ntype Server struct{}\n\nfunc (s Server) Addr() string { return \"\" }\n\nvar _ face.Worker = Server{}\n")
	writeFile(t, directory, "pkg/consumer/use.go",
		"package consumer\n\nimport \"testmodule/pkg/types\"\n\nfunc Example() string {\n\t_ = types.StrayConst\n\n\treturn types.DirPath()\n}\n")

	return directory
}

func writeFile(t *testing.T, base string, path string, content string) {
	t.Helper()
	full := filepath.Join(base, path)
	e := os.MkdirAll(filepath.Dir(full), 0755)

	if e != nil {
		t.Fatal(e)
	}

	e = os.WriteFile(full, []byte(content), 0644)

	if e != nil {
		t.Fatal(e)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, e := os.ReadFile(path)

	if e != nil {
		t.Fatal(e)
	}

	return string(b)
}
