package goanalyze

import (
	"github.com/funtimecoding/go-library/pkg/assert"
	"go/token"
	"os"
	"path/filepath"
	"testing"
)

func TestFix(t *testing.T) {
	directory := writeTestModule(t)
	fileSet := token.NewFileSet()
	all := load(fileSet, directory, []string{"./..."})
	violations := findViolations(all)
	edits := buildAllEdits(all, violations)
	applyEdits(fileSet, edits, directory, false)
	t.Run(
		"CrossPackageRename", func(t *testing.T) {
			assert.String(
				t,
				"package types\n\nfunc DirectoryPath() string { return directoryName }\n",
				readFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"types",
						"directory_path.go",
					),
				),
			)
			assert.String(
				t,
				"package types\n\nvar directoryName = \"test\"\n",
				readFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"types",
						"directory_name.go",
					),
				),
			)
			assert.String(
				t,
				"package types\n\nconst StrayConstant = \"value\"\n",
				readFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"types",
						"stray_const.go",
					),
				),
			)
			assert.String(
				t,
				"package consumer\n\nimport \"testmodule/pkg/types\"\n\nfunc Example() string {\n\t_ = types.StrayConstant\n\n\treturn types.DirectoryPath()\n}\n",
				readFile(
					t,
					filepath.Join(directory, "pkg", "consumer", "use.go"),
				),
			)
		},
	)
	t.Run(
		"SkipsInterfaceMethod", func(t *testing.T) {
			assert.String(
				t,
				"package impl\n\nimport \"testmodule/pkg/face\"\n\ntype Server struct{}\n\nfunc (s Server) Addr() string { return \"\" }\n\nvar _ face.Worker = Server{}\n",
				readFile(
					t,
					filepath.Join(directory, "pkg", "impl", "impl.go"),
				),
			)
		},
	)
	t.Run(
		"SkipsGeneratedFile", func(t *testing.T) {
			assert.String(
				t,
				"package types\n\n// Code generated by tool DO NOT EDIT.\n\ntype ParamError struct{}\n",
				readFile(
					t,
					filepath.Join(directory, "pkg", "types", "generated.go"),
				),
			)
		},
	)
	t.Run(
		"StructFieldGetsMultiCharacter", func(t *testing.T) {
			assert.String(
				t,
				"package fields\n\ntype Entry struct {\n\tReference string\n}\n",
				readFile(
					t,
					filepath.Join(directory, "pkg", "fields", "entry.go"),
				),
			)
		},
	)
	t.Run(
		"MultiSegmentPrefersMultiCharacter", func(t *testing.T) {
			assert.String(
				t,
				"package multi\n\nfunc Example() string {\n\tfooReference := \"x\"\n\n\treturn fooReference\n}\n",
				readFile(
					t,
					filepath.Join(directory, "pkg", "multi", "example.go"),
				),
			)
		},
	)
	t.Run(
		"SingleLetterCollisionFallback", func(t *testing.T) {
			assert.String(
				t,
				"package collision\n\nfunc Example() string {\n\tr := \"taken\"\n\te := \"test\"\n\n\treturn r + e\n}\n",
				readFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"collision",
						"example.go",
					),
				),
			)
		},
	)
	t.Run(
		"CollisionAbort", func(t *testing.T) {
			assert.String(
				t,
				"package abort\n\nfunc Example() string {\n\tt := \"taken\"\n\ttx := \"test\"\n\n\treturn t + tx\n}\n",
				readFile(
					t,
					filepath.Join(directory, "pkg", "abort", "example.go"),
				),
			)
		},
	)
	t.Run(
		"InnerScopeShadow", func(t *testing.T) {
			assert.String(
				t,
				"package shadow\n\nfunc Example() string {\n\tm := map[string]string{\"k\": \"x\"}\n\n\tfor _, a := range m {\n\t\tv := a\n\t\t_ = v\n\t}\n\n\treturn \"\"\n}\n",
				readFile(
					t,
					filepath.Join(directory, "pkg", "shadow", "example.go"),
				),
			)
		},
	)
	t.Run(
		"ParentScopeShadow", func(t *testing.T) {
			assert.String(
				t,
				"package parent\n\nfunc Example() {\n\ts := \"status\"\n\tsources := []string{\"a\"}\n\n\tfor _, o := range sources {\n\t\t_ = s + o\n\t}\n}\n",
				readFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"parent",
						"example.go",
					),
				),
			)
		},
	)
}

func writeTestModule(t *testing.T) string {
	t.Helper()
	directory := t.TempDir()
	writeFile(t, directory, "go.mod", "module testmodule\n\ngo 1.22\n")
	writeFile(
		t, directory, "pkg/types/directory_path.go",
		"package types\n\nfunc DirPath() string { return dirName }\n",
	)
	writeFile(
		t, directory, "pkg/types/directory_name.go",
		"package types\n\nvar dirName = \"test\"\n",
	)
	writeFile(
		t, directory, "pkg/types/stray_const.go",
		"package types\n\nconst StrayConst = \"value\"\n",
	)
	writeFile(
		t,
		directory,
		"pkg/types/generated.go",
		"package types\n\n// Code generated by tool DO NOT EDIT.\n\ntype ParamError struct{}\n",
	)
	writeFile(
		t, directory, "pkg/face/worker.go",
		"package face\n\ntype Worker interface {\n\tAddr() string\n}\n",
	)
	writeFile(
		t,
		directory,
		"pkg/impl/impl.go",
		"package impl\n\nimport \"testmodule/pkg/face\"\n\ntype Server struct{}\n\nfunc (s Server) Addr() string { return \"\" }\n\nvar _ face.Worker = Server{}\n",
	)
	writeFile(
		t,
		directory,
		"pkg/consumer/use.go",
		"package consumer\n\nimport \"testmodule/pkg/types\"\n\nfunc Example() string {\n\t_ = types.StrayConst\n\n\treturn types.DirPath()\n}\n",
	)
	writeFile(
		t,
		directory,
		"pkg/fields/entry.go",
		"package fields\n\ntype Entry struct {\n\tRef string\n}\n",
	)
	writeFile(
		t,
		directory,
		"pkg/multi/example.go",
		"package multi\n\nfunc Example() string {\n\tfooRef := \"x\"\n\n\treturn fooRef\n}\n",
	)
	writeFile(
		t,
		directory,
		"pkg/collision/example.go",
		"package collision\n\nfunc Example() string {\n\tr := \"taken\"\n\tref := \"test\"\n\n\treturn r + ref\n}\n",
	)
	writeFile(
		t,
		directory,
		"pkg/abort/example.go",
		"package abort\n\nfunc Example() string {\n\tt := \"taken\"\n\ttx := \"test\"\n\n\treturn t + tx\n}\n",
	)
	writeFile(
		t,
		directory,
		"pkg/shadow/example.go",
		"package shadow\n\nfunc Example() string {\n\tm := map[string]string{\"k\": \"x\"}\n\n\tfor _, val := range m {\n\t\tv := val\n\t\t_ = v\n\t}\n\n\treturn \"\"\n}\n",
	)
	writeFile(
		t,
		directory,
		"pkg/parent/example.go",
		"package parent\n\nfunc Example() {\n\ts := \"status\"\n\tsources := []string{\"a\"}\n\n\tfor _, src := range sources {\n\t\t_ = s + src\n\t}\n}\n",
	)

	return directory
}

func writeFile(
	t *testing.T,
	base string,
	path string,
	content string,
) {
	t.Helper()
	full := filepath.Join(base, path)
	e := os.MkdirAll(filepath.Dir(full), 0755)

	if e != nil {
		t.Fatal(e)
	}

	e = os.WriteFile(full, []byte(content), 0644)

	if e != nil {
		t.Fatal(e)
	}
}

func readFile(
	t *testing.T,
	path string,
) string {
	t.Helper()
	b, e := os.ReadFile(path)

	if e != nil {
		t.Fatal(e)
	}

	return string(b)
}
