//go:build go1.22

// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateTaskRequestType.
const (
	Daily  CreateTaskRequestType = "daily"
	Habit  CreateTaskRequestType = "habit"
	Reward CreateTaskRequestType = "reward"
	Todo   CreateTaskRequestType = "todo"
)

// Valid indicates whether the value is a known member of the CreateTaskRequestType enum.
func (e CreateTaskRequestType) Valid() bool {
	switch e {
	case Daily:
		return true
	case Habit:
		return true
	case Reward:
		return true
	case Todo:
		return true
	default:
		return false
	}
}

// Defines values for GetTasksParamsType.
const (
	Dailys  GetTasksParamsType = "dailys"
	Habits  GetTasksParamsType = "habits"
	Rewards GetTasksParamsType = "rewards"
	Todos   GetTasksParamsType = "todos"
)

// Valid indicates whether the value is a known member of the GetTasksParamsType enum.
func (e GetTasksParamsType) Valid() bool {
	switch e {
	case Dailys:
		return true
	case Habits:
		return true
	case Rewards:
		return true
	case Todos:
		return true
	default:
		return false
	}
}

// Defines values for ScoreTaskParamsDirection.
const (
	Down ScoreTaskParamsDirection = "down"
	Up   ScoreTaskParamsDirection = "up"
)

// Valid indicates whether the value is a known member of the ScoreTaskParamsDirection enum.
func (e ScoreTaskParamsDirection) Valid() bool {
	switch e {
	case Down:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// ChecklistItem defines model for ChecklistItem.
type ChecklistItem struct {
	Completed  bool   `json:"completed"`
	Identifier string `json:"identifier"`
	Text       string `json:"text"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	// Notes Task notes.
	Notes *string `json:"notes,omitempty"`

	// Text Task title.
	Text string `json:"text"`

	// Type Task type.
	Type CreateTaskRequestType `json:"type"`
}

// CreateTaskRequestType Task type.
type CreateTaskRequestType string

// CronResult defines model for CronResult.
type CronResult struct {
	After      *Stats `json:"after,omitempty"`
	Before     *Stats `json:"before,omitempty"`
	LastCron   string `json:"last_cron"`
	RolledOver bool   `json:"rolled_over"`
}

// ScoreResult defines model for ScoreResult.
type ScoreResult struct {
	Gp    float32 `json:"gp"`
	Hp    float32 `json:"hp"`
	Level int     `json:"level"`
	Mp    float32 `json:"mp"`
	Xp    float32 `json:"xp"`
}

// Stats defines model for Stats.
type Stats struct {
	Class string  `json:"class"`
	Gp    float32 `json:"gp"`
	Hp    float32 `json:"hp"`
	Level int     `json:"level"`
	Mp    float32 `json:"mp"`
	Xp    float32 `json:"xp"`
}

// Tag defines model for Tag.
type Tag struct {
	Identifier string `json:"identifier"`
	Name       string `json:"name"`
}

// Task defines model for Task.
type Task struct {
	Checklist  *[]ChecklistItem `json:"checklist,omitempty"`
	Completed  *bool            `json:"completed,omitempty"`
	Identifier string           `json:"identifier"`
	Notes      *string          `json:"notes,omitempty"`
	Streak     *int             `json:"streak,omitempty"`
	Tags       *[]string        `json:"tags,omitempty"`
	Text       string           `json:"text"`
	Type       string           `json:"type"`
	Value      *float32         `json:"value,omitempty"`
}

// GetTasksParams defines parameters for GetTasks.
type GetTasksParams struct {
	// Type Task type filter.
	Type *GetTasksParamsType `form:"type,omitempty" json:"type,omitempty"`
}

// GetTasksParamsType defines parameters for GetTasks.
type GetTasksParamsType string

// ScoreTaskParamsDirection defines parameters for ScoreTask.
type ScoreTaskParamsDirection string

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/cron)
	RunCron(w http.ResponseWriter, r *http.Request)

	// (GET /api/stats)
	GetStats(w http.ResponseWriter, r *http.Request)

	// (GET /api/tags)
	GetTags(w http.ResponseWriter, r *http.Request)

	// (GET /api/tasks)
	GetTasks(w http.ResponseWriter, r *http.Request, params GetTasksParams)

	// (POST /api/tasks)
	CreateTask(w http.ResponseWriter, r *http.Request)

	// (POST /api/tasks/{identifier}/score/{direction})
	ScoreTask(w http.ResponseWriter, r *http.Request, identifier string, direction ScoreTaskParamsDirection)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RunCron operation middleware
func (siw *ServerInterfaceWrapper) RunCron(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunCron(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTags operation middleware
func (siw *ServerInterfaceWrapper) GetTags(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTags(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTasks operation middleware
func (siw *ServerInterfaceWrapper) GetTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTasksParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ScoreTask operation middleware
func (siw *ServerInterfaceWrapper) ScoreTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier string

	err = runtime.BindStyledParameterWithOptions("simple", "identifier", r.PathValue("identifier"), &identifier, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	// ------------- Path parameter "direction" -------------
	var direction ScoreTaskParamsDirection

	err = runtime.BindStyledParameterWithOptions("simple", "direction", r.PathValue("direction"), &direction, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "direction", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ScoreTask(w, r, identifier, direction)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/cron", wrapper.RunCron)
	m.HandleFunc("GET "+options.BaseURL+"/api/stats", wrapper.GetStats)
	m.HandleFunc("GET "+options.BaseURL+"/api/tags", wrapper.GetTags)
	m.HandleFunc("GET "+options.BaseURL+"/api/tasks", wrapper.GetTasks)
	m.HandleFunc("POST "+options.BaseURL+"/api/tasks", wrapper.CreateTask)
	m.HandleFunc("POST "+options.BaseURL+"/api/tasks/{identifier}/score/{direction}", wrapper.ScoreTask)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWwY7bNhD9FYHtUbA2bU+6tSlQ7KGXzfYUBAEtjSTGFMnljHZjGPr3YijLkiwq3iJJ",
	"kZut4QzfGz4+zkkUtnXWgCEU+Ulg0UArw8+3DRQHrZDuCVr+4Lx14ElBCHOeBoKS/9DRgcjF3loN0og+",
	"FaoEQ6pS4GdxJK9MzWGCzxQJ9Knw8NQpz2Xfz4ucU9LZvh/SMd3uP0FBXPetB0nwKPHwAE8dIK2BG0vD",
	"jxKw8MqRskbkgnOSENuJdBtwJIkUaYgnhQ/xpKMLOWC6lqk2cq+YXimVPnItW1rB3XiRfk51o1MhekYZ",
	"74s1D4CdjjREVjSc0s8eKpGLn7JJE9lZENk7koRcaQ+V9fDq5VoifSw8E4/IwFutofxonxcyucjoiuR8",
	"9bxyjPC7wnrYYly72W6ma/fgOaeJf9bwDHoWUYagHkJtPONz7PMVmcaJkB9Wpwxp3ClKJ/RzfQm1RIx2",
	"9semmJ6Rx6g+ynpN9IadGNnCf7STkBLfHw+RTo9uGNAQtHjrCiz98+IGQnovj/z/6xz0YmOrCJIHeYif",
	"JskaFww2PGtCueHUk7mtAs9Sd3BbHTFzDxnrQ+FUZSobirLbilzUtpH7UqTiGTwOxvpmd7e7YwTWgZFO",
	"iVz8Gj6lwklqAt9MOpWNfuTscJ580JLd+b4UuXjoDNtlcF901uDQ51/u7oZ3zxCYkCad06oIidknHEoO",
	"p39TG5MdB3LLB4KjiQ/h5EVRk9gQkTpBkpSUqqp2nNenAx0czaGGCJ2/gAb3+I58zna/pvIPgg+ocYF4",
	"lOEW4EeOfyXeV11SNpuV6Nc0ftc6YcxXJPBwgwUvYPF52QKBR5G/35wGkkppAs9DgeLAUwf+OBpVPr7w",
	"E7/F5IDj6IDn2QEvwwPGpocP/09z8fCa7oY+Ja2kolGmTqiZehFWx6/pNOqJwVgA6Q9bHr/hJb2eJful",
	"h5HvoF818s03AzD0L+YPDKxMWIA7bvBvw+ktV/2tELmdI96kUqDLiISz02TFfYY8OGWnUnkouFK/bZRh",
	"xjofwG2N3/95kTa78aTsxUOw7O5c76u3/XqXACe5AN/Y7RL/4mbj5ep4Zinti/kel+iLjjqbXyMSGLjO",
	"34jOlUEUM7Pt+38DAAD///hrm1jfDQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
