// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// CommentRequest defines model for CommentRequest.
type CommentRequest struct {
	// Body Comment body text.
	Body string `json:"body"`
}

// ConfluencePage defines model for ConfluencePage.
type ConfluencePage struct {
	Identifier string  `json:"identifier"`
	Link       *string `json:"link,omitempty"`
	Status     *string `json:"status,omitempty"`
	Title      string  `json:"title"`
	Type       *string `json:"type,omitempty"`
}

// ConfluencePageDetail defines model for ConfluencePageDetail.
type ConfluencePageDetail struct {
	Body            *string `json:"body,omitempty"`
	Identifier      string  `json:"identifier"`
	Link            *string `json:"link,omitempty"`
	SpaceIdentifier *string `json:"spaceIdentifier,omitempty"`
	Title           string  `json:"title"`
}

// ConfluenceSpace defines model for ConfluenceSpace.
type ConfluenceSpace struct {
	Description        *string `json:"description,omitempty"`
	HomepageIdentifier *string `json:"homepageIdentifier,omitempty"`
	Identifier         string  `json:"identifier"`
	Key                string  `json:"key"`
	Name               string  `json:"name"`
	Type               *string `json:"type,omitempty"`
}

// CreatePageRequest defines model for CreatePageRequest.
type CreatePageRequest struct {
	// Body Page content in markdown.
	Body string `json:"body"`

	// ParentIdentifier Parent page ID.
	ParentIdentifier string `json:"parentIdentifier"`

	// SpaceIdentifier Space ID to create the page in.
	SpaceIdentifier string `json:"spaceIdentifier"`

	// Title Page title.
	Title string `json:"title"`
}

// JiraIssue defines model for JiraIssue.
type JiraIssue struct {
	Assignee    *string   `json:"assignee,omitempty"`
	Created     *string   `json:"created,omitempty"`
	Description *string   `json:"description,omitempty"`
	Due         *string   `json:"due,omitempty"`
	Key         string    `json:"key"`
	Labels      *[]string `json:"labels,omitempty"`
	Link        *string   `json:"link,omitempty"`
	Priority    *string   `json:"priority,omitempty"`
	Status      string    `json:"status"`
	Summary     string    `json:"summary"`
	Type        string    `json:"type"`
}

// JiraProject defines model for JiraProject.
type JiraProject struct {
	Description *string `json:"description,omitempty"`
	Key         string  `json:"key"`
	Link        *string `json:"link,omitempty"`
	Name        string  `json:"name"`
	Type        *string `json:"type,omitempty"`
}

// JiraTransition defines model for JiraTransition.
type JiraTransition struct {
	Identifier string  `json:"identifier"`
	Name       string  `json:"name"`
	ToStatus   *string `json:"toStatus,omitempty"`
}

// TransitionRequest defines model for TransitionRequest.
type TransitionRequest struct {
	// TransitionIdentifier Transition ID from get_transitions.
	TransitionIdentifier string `json:"transitionIdentifier"`
}

// UpdatePageRequest defines model for UpdatePageRequest.
type UpdatePageRequest struct {
	// Body Page content in markdown.
	Body string `json:"body"`

	// Message Version comment.
	Message *string `json:"message,omitempty"`

	// Title Page title.
	Title string `json:"title"`
}

// SearchPagesParams defines parameters for SearchPages.
type SearchPagesParams struct {
	// Query CQL query string or plain text.
	Query string `form:"query" json:"query"`
}

// SearchIssuesParams defines parameters for SearchIssues.
type SearchIssuesParams struct {
	// Query JQL query string.
	Query string `form:"query" json:"query"`

	// Limit Maximum number of results. Omit for all.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreatePageJSONRequestBody defines body for CreatePage for application/json ContentType.
type CreatePageJSONRequestBody = CreatePageRequest

// UpdatePageJSONRequestBody defines body for UpdatePage for application/json ContentType.
type UpdatePageJSONRequestBody = UpdatePageRequest

// AddPageCommentJSONRequestBody defines body for AddPageComment for application/json ContentType.
type AddPageCommentJSONRequestBody = CommentRequest

// AddIssueCommentJSONRequestBody defines body for AddIssueComment for application/json ContentType.
type AddIssueCommentJSONRequestBody = CommentRequest

// TransitionIssueJSONRequestBody defines body for TransitionIssue for application/json ContentType.
type TransitionIssueJSONRequestBody = TransitionRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreatePageWithBody request with any body
	CreatePageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePage(ctx context.Context, body CreatePageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPage request
	GetPage(ctx context.Context, identifier string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdatePageWithBody request with any body
	UpdatePageWithBody(ctx context.Context, identifier string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdatePage(ctx context.Context, identifier string, body UpdatePageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPageChildren request
	GetPageChildren(ctx context.Context, identifier string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddPageCommentWithBody request with any body
	AddPageCommentWithBody(ctx context.Context, identifier string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddPageComment(ctx context.Context, identifier string, body AddPageCommentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchPages request
	SearchPages(ctx context.Context, params *SearchPagesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSpaces request
	ListSpaces(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetIssue request
	GetIssue(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddIssueCommentWithBody request with any body
	AddIssueCommentWithBody(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddIssueComment(ctx context.Context, key string, body AddIssueCommentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TransitionIssueWithBody request with any body
	TransitionIssueWithBody(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TransitionIssue(ctx context.Context, key string, body TransitionIssueJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTransitions request
	GetTransitions(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListProjects request
	ListProjects(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchIssues request
	SearchIssues(ctx context.Context, params *SearchIssuesParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreatePageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePageRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePage(ctx context.Context, body CreatePageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePageRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPage(ctx context.Context, identifier string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPageRequest(c.Server, identifier)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdatePageWithBody(ctx context.Context, identifier string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdatePageRequestWithBody(c.Server, identifier, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdatePage(ctx context.Context, identifier string, body UpdatePageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdatePageRequest(c.Server, identifier, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPageChildren(ctx context.Context, identifier string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPageChildrenRequest(c.Server, identifier)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddPageCommentWithBody(ctx context.Context, identifier string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddPageCommentRequestWithBody(c.Server, identifier, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddPageComment(ctx context.Context, identifier string, body AddPageCommentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddPageCommentRequest(c.Server, identifier, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchPages(ctx context.Context, params *SearchPagesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchPagesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSpaces(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSpacesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetIssue(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetIssueRequest(c.Server, key)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddIssueCommentWithBody(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddIssueCommentRequestWithBody(c.Server, key, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddIssueComment(ctx context.Context, key string, body AddIssueCommentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddIssueCommentRequest(c.Server, key, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TransitionIssueWithBody(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTransitionIssueRequestWithBody(c.Server, key, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TransitionIssue(ctx context.Context, key string, body TransitionIssueJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTransitionIssueRequest(c.Server, key, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTransitions(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTransitionsRequest(c.Server, key)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListProjects(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListProjectsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchIssues(ctx context.Context, params *SearchIssuesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchIssuesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreatePageRequest calls the generic CreatePage builder with application/json body
func NewCreatePageRequest(server string, body CreatePageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePageRequestWithBody(server, "application/json", bodyReader)
}

// NewCreatePageRequestWithBody generates requests for CreatePage with any type of body
func NewCreatePageRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/confluence/page")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPageRequest generates requests for GetPage
func NewGetPageRequest(server string, identifier string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "identifier", identifier, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/confluence/page/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdatePageRequest calls the generic UpdatePage builder with application/json body
func NewUpdatePageRequest(server string, identifier string, body UpdatePageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdatePageRequestWithBody(server, identifier, "application/json", bodyReader)
}

// NewUpdatePageRequestWithBody generates requests for UpdatePage with any type of body
func NewUpdatePageRequestWithBody(server string, identifier string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "identifier", identifier, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/confluence/page/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPageChildrenRequest generates requests for GetPageChildren
func NewGetPageChildrenRequest(server string, identifier string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "identifier", identifier, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/confluence/page/%s/children", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddPageCommentRequest calls the generic AddPageComment builder with application/json body
func NewAddPageCommentRequest(server string, identifier string, body AddPageCommentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddPageCommentRequestWithBody(server, identifier, "application/json", bodyReader)
}

// NewAddPageCommentRequestWithBody generates requests for AddPageComment with any type of body
func NewAddPageCommentRequestWithBody(server string, identifier string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "identifier", identifier, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/confluence/page/%s/comment", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSearchPagesRequest generates requests for SearchPages
func NewSearchPagesRequest(server string, params *SearchPagesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/confluence/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "query", params.Query, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListSpacesRequest generates requests for ListSpaces
func NewListSpacesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/confluence/spaces")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetIssueRequest generates requests for GetIssue
func NewGetIssueRequest(server string, key string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "key", key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jira/issue/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddIssueCommentRequest calls the generic AddIssueComment builder with application/json body
func NewAddIssueCommentRequest(server string, key string, body AddIssueCommentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddIssueCommentRequestWithBody(server, key, "application/json", bodyReader)
}

// NewAddIssueCommentRequestWithBody generates requests for AddIssueComment with any type of body
func NewAddIssueCommentRequestWithBody(server string, key string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "key", key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jira/issue/%s/comment", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTransitionIssueRequest calls the generic TransitionIssue builder with application/json body
func NewTransitionIssueRequest(server string, key string, body TransitionIssueJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTransitionIssueRequestWithBody(server, key, "application/json", bodyReader)
}

// NewTransitionIssueRequestWithBody generates requests for TransitionIssue with any type of body
func NewTransitionIssueRequestWithBody(server string, key string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "key", key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jira/issue/%s/transition", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTransitionsRequest generates requests for GetTransitions
func NewGetTransitionsRequest(server string, key string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "key", key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jira/issue/%s/transitions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListProjectsRequest generates requests for ListProjects
func NewListProjectsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jira/projects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSearchIssuesRequest generates requests for SearchIssues
func NewSearchIssuesRequest(server string, params *SearchIssuesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jira/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "query", params.Query, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreatePageWithBodyWithResponse request with any body
	CreatePageWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePageResponse, error)

	CreatePageWithResponse(ctx context.Context, body CreatePageJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePageResponse, error)

	// GetPageWithResponse request
	GetPageWithResponse(ctx context.Context, identifier string, reqEditors ...RequestEditorFn) (*GetPageResponse, error)

	// UpdatePageWithBodyWithResponse request with any body
	UpdatePageWithBodyWithResponse(ctx context.Context, identifier string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdatePageResponse, error)

	UpdatePageWithResponse(ctx context.Context, identifier string, body UpdatePageJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdatePageResponse, error)

	// GetPageChildrenWithResponse request
	GetPageChildrenWithResponse(ctx context.Context, identifier string, reqEditors ...RequestEditorFn) (*GetPageChildrenResponse, error)

	// AddPageCommentWithBodyWithResponse request with any body
	AddPageCommentWithBodyWithResponse(ctx context.Context, identifier string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddPageCommentResponse, error)

	AddPageCommentWithResponse(ctx context.Context, identifier string, body AddPageCommentJSONRequestBody, reqEditors ...RequestEditorFn) (*AddPageCommentResponse, error)

	// SearchPagesWithResponse request
	SearchPagesWithResponse(ctx context.Context, params *SearchPagesParams, reqEditors ...RequestEditorFn) (*SearchPagesResponse, error)

	// ListSpacesWithResponse request
	ListSpacesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSpacesResponse, error)

	// GetIssueWithResponse request
	GetIssueWithResponse(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*GetIssueResponse, error)

	// AddIssueCommentWithBodyWithResponse request with any body
	AddIssueCommentWithBodyWithResponse(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddIssueCommentResponse, error)

	AddIssueCommentWithResponse(ctx context.Context, key string, body AddIssueCommentJSONRequestBody, reqEditors ...RequestEditorFn) (*AddIssueCommentResponse, error)

	// TransitionIssueWithBodyWithResponse request with any body
	TransitionIssueWithBodyWithResponse(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TransitionIssueResponse, error)

	TransitionIssueWithResponse(ctx context.Context, key string, body TransitionIssueJSONRequestBody, reqEditors ...RequestEditorFn) (*TransitionIssueResponse, error)

	// GetTransitionsWithResponse request
	GetTransitionsWithResponse(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*GetTransitionsResponse, error)

	// ListProjectsWithResponse request
	ListProjectsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListProjectsResponse, error)

	// SearchIssuesWithResponse request
	SearchIssuesWithResponse(ctx context.Context, params *SearchIssuesParams, reqEditors ...RequestEditorFn) (*SearchIssuesResponse, error)
}

type CreatePageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ConfluencePageDetail
}

// Status returns HTTPResponse.Status
func (r CreatePageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConfluencePageDetail
}

// Status returns HTTPResponse.Status
func (r GetPageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdatePageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConfluencePageDetail
}

// Status returns HTTPResponse.Status
func (r UpdatePageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdatePageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPageChildrenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ConfluencePage
}

// Status returns HTTPResponse.Status
func (r GetPageChildrenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPageChildrenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddPageCommentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r AddPageCommentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddPageCommentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SearchPagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ConfluencePage
}

// Status returns HTTPResponse.Status
func (r SearchPagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchPagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListSpacesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ConfluenceSpace
}

// Status returns HTTPResponse.Status
func (r ListSpacesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSpacesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetIssueResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JiraIssue
}

// Status returns HTTPResponse.Status
func (r GetIssueResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetIssueResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddIssueCommentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r AddIssueCommentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddIssueCommentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TransitionIssueResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TransitionIssueResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TransitionIssueResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTransitionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]JiraTransition
}

// Status returns HTTPResponse.Status
func (r GetTransitionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTransitionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListProjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]JiraProject
}

// Status returns HTTPResponse.Status
func (r ListProjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListProjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SearchIssuesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]JiraIssue
}

// Status returns HTTPResponse.Status
func (r SearchIssuesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchIssuesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreatePageWithBodyWithResponse request with arbitrary body returning *CreatePageResponse
func (c *ClientWithResponses) CreatePageWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePageResponse, error) {
	rsp, err := c.CreatePageWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePageResponse(rsp)
}

func (c *ClientWithResponses) CreatePageWithResponse(ctx context.Context, body CreatePageJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePageResponse, error) {
	rsp, err := c.CreatePage(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePageResponse(rsp)
}

// GetPageWithResponse request returning *GetPageResponse
func (c *ClientWithResponses) GetPageWithResponse(ctx context.Context, identifier string, reqEditors ...RequestEditorFn) (*GetPageResponse, error) {
	rsp, err := c.GetPage(ctx, identifier, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPageResponse(rsp)
}

// UpdatePageWithBodyWithResponse request with arbitrary body returning *UpdatePageResponse
func (c *ClientWithResponses) UpdatePageWithBodyWithResponse(ctx context.Context, identifier string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdatePageResponse, error) {
	rsp, err := c.UpdatePageWithBody(ctx, identifier, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdatePageResponse(rsp)
}

func (c *ClientWithResponses) UpdatePageWithResponse(ctx context.Context, identifier string, body UpdatePageJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdatePageResponse, error) {
	rsp, err := c.UpdatePage(ctx, identifier, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdatePageResponse(rsp)
}

// GetPageChildrenWithResponse request returning *GetPageChildrenResponse
func (c *ClientWithResponses) GetPageChildrenWithResponse(ctx context.Context, identifier string, reqEditors ...RequestEditorFn) (*GetPageChildrenResponse, error) {
	rsp, err := c.GetPageChildren(ctx, identifier, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPageChildrenResponse(rsp)
}

// AddPageCommentWithBodyWithResponse request with arbitrary body returning *AddPageCommentResponse
func (c *ClientWithResponses) AddPageCommentWithBodyWithResponse(ctx context.Context, identifier string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddPageCommentResponse, error) {
	rsp, err := c.AddPageCommentWithBody(ctx, identifier, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddPageCommentResponse(rsp)
}

func (c *ClientWithResponses) AddPageCommentWithResponse(ctx context.Context, identifier string, body AddPageCommentJSONRequestBody, reqEditors ...RequestEditorFn) (*AddPageCommentResponse, error) {
	rsp, err := c.AddPageComment(ctx, identifier, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddPageCommentResponse(rsp)
}

// SearchPagesWithResponse request returning *SearchPagesResponse
func (c *ClientWithResponses) SearchPagesWithResponse(ctx context.Context, params *SearchPagesParams, reqEditors ...RequestEditorFn) (*SearchPagesResponse, error) {
	rsp, err := c.SearchPages(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchPagesResponse(rsp)
}

// ListSpacesWithResponse request returning *ListSpacesResponse
func (c *ClientWithResponses) ListSpacesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSpacesResponse, error) {
	rsp, err := c.ListSpaces(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSpacesResponse(rsp)
}

// GetIssueWithResponse request returning *GetIssueResponse
func (c *ClientWithResponses) GetIssueWithResponse(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*GetIssueResponse, error) {
	rsp, err := c.GetIssue(ctx, key, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetIssueResponse(rsp)
}

// AddIssueCommentWithBodyWithResponse request with arbitrary body returning *AddIssueCommentResponse
func (c *ClientWithResponses) AddIssueCommentWithBodyWithResponse(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddIssueCommentResponse, error) {
	rsp, err := c.AddIssueCommentWithBody(ctx, key, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddIssueCommentResponse(rsp)
}

func (c *ClientWithResponses) AddIssueCommentWithResponse(ctx context.Context, key string, body AddIssueCommentJSONRequestBody, reqEditors ...RequestEditorFn) (*AddIssueCommentResponse, error) {
	rsp, err := c.AddIssueComment(ctx, key, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddIssueCommentResponse(rsp)
}

// TransitionIssueWithBodyWithResponse request with arbitrary body returning *TransitionIssueResponse
func (c *ClientWithResponses) TransitionIssueWithBodyWithResponse(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TransitionIssueResponse, error) {
	rsp, err := c.TransitionIssueWithBody(ctx, key, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTransitionIssueResponse(rsp)
}

func (c *ClientWithResponses) TransitionIssueWithResponse(ctx context.Context, key string, body TransitionIssueJSONRequestBody, reqEditors ...RequestEditorFn) (*TransitionIssueResponse, error) {
	rsp, err := c.TransitionIssue(ctx, key, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTransitionIssueResponse(rsp)
}

// GetTransitionsWithResponse request returning *GetTransitionsResponse
func (c *ClientWithResponses) GetTransitionsWithResponse(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*GetTransitionsResponse, error) {
	rsp, err := c.GetTransitions(ctx, key, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTransitionsResponse(rsp)
}

// ListProjectsWithResponse request returning *ListProjectsResponse
func (c *ClientWithResponses) ListProjectsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListProjectsResponse, error) {
	rsp, err := c.ListProjects(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListProjectsResponse(rsp)
}

// SearchIssuesWithResponse request returning *SearchIssuesResponse
func (c *ClientWithResponses) SearchIssuesWithResponse(ctx context.Context, params *SearchIssuesParams, reqEditors ...RequestEditorFn) (*SearchIssuesResponse, error) {
	rsp, err := c.SearchIssues(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchIssuesResponse(rsp)
}

// ParseCreatePageResponse parses an HTTP response from a CreatePageWithResponse call
func ParseCreatePageResponse(rsp *http.Response) (*CreatePageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ConfluencePageDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseGetPageResponse parses an HTTP response from a GetPageWithResponse call
func ParseGetPageResponse(rsp *http.Response) (*GetPageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConfluencePageDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUpdatePageResponse parses an HTTP response from a UpdatePageWithResponse call
func ParseUpdatePageResponse(rsp *http.Response) (*UpdatePageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdatePageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConfluencePageDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetPageChildrenResponse parses an HTTP response from a GetPageChildrenWithResponse call
func ParseGetPageChildrenResponse(rsp *http.Response) (*GetPageChildrenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPageChildrenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ConfluencePage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAddPageCommentResponse parses an HTTP response from a AddPageCommentWithResponse call
func ParseAddPageCommentResponse(rsp *http.Response) (*AddPageCommentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddPageCommentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseSearchPagesResponse parses an HTTP response from a SearchPagesWithResponse call
func ParseSearchPagesResponse(rsp *http.Response) (*SearchPagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchPagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ConfluencePage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListSpacesResponse parses an HTTP response from a ListSpacesWithResponse call
func ParseListSpacesResponse(rsp *http.Response) (*ListSpacesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSpacesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ConfluenceSpace
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetIssueResponse parses an HTTP response from a GetIssueWithResponse call
func ParseGetIssueResponse(rsp *http.Response) (*GetIssueResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetIssueResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JiraIssue
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAddIssueCommentResponse parses an HTTP response from a AddIssueCommentWithResponse call
func ParseAddIssueCommentResponse(rsp *http.Response) (*AddIssueCommentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddIssueCommentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTransitionIssueResponse parses an HTTP response from a TransitionIssueWithResponse call
func ParseTransitionIssueResponse(rsp *http.Response) (*TransitionIssueResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TransitionIssueResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetTransitionsResponse parses an HTTP response from a GetTransitionsWithResponse call
func ParseGetTransitionsResponse(rsp *http.Response) (*GetTransitionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTransitionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []JiraTransition
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListProjectsResponse parses an HTTP response from a ListProjectsWithResponse call
func ParseListProjectsResponse(rsp *http.Response) (*ListProjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListProjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []JiraProject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSearchIssuesResponse parses an HTTP response from a SearchIssuesWithResponse call
func ParseSearchIssuesResponse(rsp *http.Response) (*SearchIssuesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchIssuesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []JiraIssue
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
