package tag

const (
	Age         = "age"
	Assignee    = "assignee"
	Category    = "category"
	Concerns    = "concerns"
	Dense       = "dense"
	Description = "description"
	Emoji       = "emoji"
	Filter      = "filter"
	Fingerprint = "fingerprint"
	Graph       = "graph"
	Instance    = "instance"
	Investigate = "investigate"
	Key         = "key"
	Link        = "link"
	Markdown    = "markdown"
	Runbook     = "runbook"
	Score       = "score"
	State       = "state"
	Status      = "status"
	Timestamp   = "timestamp"
	Type        = "type"
	Usage       = "usage"
	Wiki        = "wiki"
)
