package tag

const (
	Age         = "age"
	Assignee    = "assignee"
	Category    = "category"
	Changes     = "changes"
	Cluster     = "cluster"
	Comment     = "comment"
	Concerns    = "concerns"
	Copyable    = "copyable"
	Dense       = "dense"
	Description = "description"
	Emoji       = "emoji"
	Filter      = "filter"
	Fingerprint = "fingerprint"
	Graph       = "graph"
	Host        = "host"
	Identifier  = "identifier"
	Instance    = "instance"
	Investigate = "investigate"
	Key         = "key"
	Markdown    = "markdown"
	Name        = "name"
	Project     = "project"
	Runbook     = "runbook"
	Score       = "score"
	State       = "state"
	Status      = "status"
	Timestamp   = "timestamp"
	Type        = "type"
	Usage       = "usage"
	Wiki        = "wiki"
)
