package strings

const (
	Alfa     = "Alfa"
	Bravo    = "Bravo"
	Charlie  = "Charlie"
	Delta    = "Delta"
	Echo     = "Echo"
	Foxtrot  = "Foxtrot"
	Golf     = "Golf"
	Hotel    = "Hotel"
	India    = "India"
	Juliett  = "Juliett"
	Kilo     = "Kilo"
	Lima     = "Lima"
	Mike     = "Mike"
	November = "November"
	Oscar    = "Oscar"
	Papa     = "Papa"
	Quebec   = "Quebec"
	Romeo    = "Romeo"
	Sierra   = "Sierra"
	Tango    = "Tango"
	Uniform  = "Uniform"
	Victor   = "Victor"
	Whiskey  = "Whiskey"
	Xray     = "Xray"
	Yankee   = "Yankee"
	Zulu     = "Zulu"
)
