package lint

import (
	"github.com/funtimecoding/go-library/pkg/assert"
	"github.com/funtimecoding/go-library/pkg/constant"
	"os"
	"path/filepath"
	"testing"
)

func TestIsGeneratedFileProtoc(t *testing.T) {
	path := writeTestFile(
		t,
		"service.pb.go",
		"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n",
	)
	assert.True(t, IsGeneratedFile(path))
}

func TestIsGeneratedFileOapiCodegen(t *testing.T) {
	path := writeTestFile(
		t,
		constant.GeneratedFile,
		"// Package client provides primitives.\n//\n// Code generated by oapi-codegen. DO NOT EDIT.\npackage client\n",
	)
	assert.True(t, IsGeneratedFile(path))
}

func TestIsGeneratedFileNormal(t *testing.T) {
	path := writeTestFile(
		t,
		"foo.go",
		"package foo\n\nfunc Foo() {}\n",
	)
	assert.Boolean(t, false, IsGeneratedFile(path))
}

func TestIsGeneratedFileNotFound(t *testing.T) {
	assert.Boolean(
		t,
		false,
		IsGeneratedFile(filepath.Join(t.TempDir(), "missing.go")),
	)
}

func writeTestFile(
	t *testing.T,
	name string,
	content string,
) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), name)
	e := os.WriteFile(path, []byte(content), 0644)

	if e != nil {
		t.Fatalf("write: %s", e)
	}

	return path
}
