//go:build go1.22

// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// ExplainRequest defines model for ExplainRequest.
type ExplainRequest struct {
	// Analyze Run EXPLAIN ANALYZE.
	Analyze *bool `json:"analyze,omitempty"`

	// Instance Instance name.
	Instance string `json:"instance"`

	// Sql SQL to explain.
	Sql string `json:"sql"`
}

// Instance defines model for Instance.
type Instance struct {
	Database string `json:"database"`
	Host     string `json:"host"`
	Name     string `json:"name"`
	Port     int    `json:"port"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	// Instance Instance name.
	Instance string `json:"instance"`

	// Sql SQL to execute.
	Sql string `json:"sql"`
}

// QueryResult defines model for QueryResult.
type QueryResult struct {
	Rows []map[string]interface{} `json:"rows"`
}

// ListIndexesParams defines parameters for ListIndexes.
type ListIndexesParams struct {
	// Instance Instance name.
	Instance string `form:"instance" json:"instance"`

	// Table Table name.
	Table string `form:"table" json:"table"`

	// Schema Schema name.
	Schema *string `form:"schema,omitempty" json:"schema,omitempty"`
}

// ListSchemasParams defines parameters for ListSchemas.
type ListSchemasParams struct {
	// Instance Instance name.
	Instance string `form:"instance" json:"instance"`
}

// TableSizesParams defines parameters for TableSizes.
type TableSizesParams struct {
	// Instance Instance name.
	Instance string `form:"instance" json:"instance"`

	// Schema Schema name.
	Schema *string `form:"schema,omitempty" json:"schema,omitempty"`
}

// ListTablesParams defines parameters for ListTables.
type ListTablesParams struct {
	// Instance Instance name.
	Instance string `form:"instance" json:"instance"`

	// Schema Schema name.
	Schema *string `form:"schema,omitempty" json:"schema,omitempty"`
}

// DescribeTableParams defines parameters for DescribeTable.
type DescribeTableParams struct {
	// Instance Instance name.
	Instance string `form:"instance" json:"instance"`

	// Schema Schema name.
	Schema *string `form:"schema,omitempty" json:"schema,omitempty"`
}

// ExplainJSONRequestBody defines body for Explain for application/json ContentType.
type ExplainJSONRequestBody = ExplainRequest

// QueryJSONRequestBody defines body for Query for application/json ContentType.
type QueryJSONRequestBody = QueryRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/v1/explain)
	Explain(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/indexes)
	ListIndexes(w http.ResponseWriter, r *http.Request, params ListIndexesParams)

	// (GET /api/v1/instances)
	ListInstances(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/query)
	Query(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/schemas)
	ListSchemas(w http.ResponseWriter, r *http.Request, params ListSchemasParams)

	// (GET /api/v1/table-sizes)
	TableSizes(w http.ResponseWriter, r *http.Request, params TableSizesParams)

	// (GET /api/v1/tables)
	ListTables(w http.ResponseWriter, r *http.Request, params ListTablesParams)

	// (GET /api/v1/tables/{table})
	DescribeTable(w http.ResponseWriter, r *http.Request, table string, params DescribeTableParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Explain operation middleware
func (siw *ServerInterfaceWrapper) Explain(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Explain(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListIndexes operation middleware
func (siw *ServerInterfaceWrapper) ListIndexes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListIndexesParams

	// ------------- Required query parameter "instance" -------------

	if paramValue := r.URL.Query().Get("instance"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "instance"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "instance", r.URL.Query(), &params.Instance, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instance", Err: err})
		return
	}

	// ------------- Required query parameter "table" -------------

	if paramValue := r.URL.Query().Get("table"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "table"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "table", r.URL.Query(), &params.Table, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	// ------------- Optional query parameter "schema" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "schema", r.URL.Query(), &params.Schema, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "schema", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListIndexes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInstances operation middleware
func (siw *ServerInterfaceWrapper) ListInstances(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInstances(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Query operation middleware
func (siw *ServerInterfaceWrapper) Query(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Query(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSchemas operation middleware
func (siw *ServerInterfaceWrapper) ListSchemas(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSchemasParams

	// ------------- Required query parameter "instance" -------------

	if paramValue := r.URL.Query().Get("instance"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "instance"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "instance", r.URL.Query(), &params.Instance, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instance", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchemas(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TableSizes operation middleware
func (siw *ServerInterfaceWrapper) TableSizes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params TableSizesParams

	// ------------- Required query parameter "instance" -------------

	if paramValue := r.URL.Query().Get("instance"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "instance"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "instance", r.URL.Query(), &params.Instance, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instance", Err: err})
		return
	}

	// ------------- Optional query parameter "schema" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "schema", r.URL.Query(), &params.Schema, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "schema", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TableSizes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTables operation middleware
func (siw *ServerInterfaceWrapper) ListTables(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTablesParams

	// ------------- Required query parameter "instance" -------------

	if paramValue := r.URL.Query().Get("instance"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "instance"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "instance", r.URL.Query(), &params.Instance, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instance", Err: err})
		return
	}

	// ------------- Optional query parameter "schema" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "schema", r.URL.Query(), &params.Schema, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "schema", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTables(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DescribeTable operation middleware
func (siw *ServerInterfaceWrapper) DescribeTable(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", r.PathValue("table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DescribeTableParams

	// ------------- Required query parameter "instance" -------------

	if paramValue := r.URL.Query().Get("instance"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "instance"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "instance", r.URL.Query(), &params.Instance, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instance", Err: err})
		return
	}

	// ------------- Optional query parameter "schema" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "schema", r.URL.Query(), &params.Schema, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "schema", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DescribeTable(w, r, table, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/v1/explain", wrapper.Explain)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/indexes", wrapper.ListIndexes)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/instances", wrapper.ListInstances)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/query", wrapper.Query)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/schemas", wrapper.ListSchemas)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/table-sizes", wrapper.TableSizes)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/tables", wrapper.ListTables)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/tables/{table}", wrapper.DescribeTable)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXS08jORD+K5Z3j73psMupb9kZDpEyCAiHmUEcnHYlMXLKju1mCKj/+8iPJJ10HgeC",
	"QCNORO16ft9XZfNCSzXTCgGdpcULteUUZiz8vHjSkgm8gXkF1vkv2igNxgkI5wyZXDyD/8lhzCrpaDFm",
	"0kJGOdjSCO2EQlrQmwrJxferQa9/SXqXvcGPnxcdmlG30EALOlJKAkNaZ1SgdQzLFLIZop9OCLIZNJyt",
	"MwIn3tfOZdtteD0gThGInezwqzNqYF4JA5wWd+sCYrz7lb0aPUDpfJ5+o8ZNPDhzbMRsOGmVN1URwtaB",
	"b2jngVam6SHQwQRMq+Tgn+Inp2xdyq4Oriswi72svh0HUFYOTsJB6sAGyW03YNSv2IiDWdQp58LXwuRV",
	"w9CZCnaETh+YMWzRKi2EbhdUB+mOVWBLOOnPJkpPOM3oIxgbcTjrdDtdn0JpQKYFLeh/4VNGNXPTUGrO",
	"tMgfz/Ik2NBcEo6vnPk2+pwWy9mksT6w7n/FF96sVOgAgwfTWooy+OQPVuF6vP2vvw2MaUH/ytfzn6fh",
	"z7cmv97EwSMXPlit0EbQ/+12T5a9yW5IvamnVBzRkmHH43kec29afRPWCpwQZYjARyYFJ5oZNgMHxnZ8",
	"3DpbwS2Qw1NsZAI70B4I6/rJxrO1jEOLu6ND4lmkc98SXQ57U+KbsGYNiFpTsp3qlo3k4TzOW7wuyTCY",
	"HsySojXDru4DqquRFOWOob9/PwUlKolC4qZAAkrHlXRIPpHOYwJaWr2y89ViOwTB6ppq77QWHj0pSalw",
	"LCaVAU5W7Wz3GXnfu5OukyzeYiNt3Fkfax+FY2LCOfE3xImWUuMltldTw2TzbkvpHac49U5EnOLlk+c4",
	"+stG19hvQx82wj9WPB8Y6bB9h8Hk41wJf+K2jtdcIIMw5H7ESKkqdPZkVB8estto8snym7O8GubodDp+",
	"85fwt97L89cQfgS36cV0kOodDy//gj/pu+tTTq+S0xclqxkSDmOB4Z+/5bI4b4sp0akcGasKeVRQXf8O",
	"AAD//6YycNUaEQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
